import type { SoundEventDefinition } from "./types";

const DEFAULT_VOLUME = 1;

export const SOUND_EVENTS: SoundEventDefinition[] = [
  {
    id: "card-drag-start",
    label: "Card drag start",
    description: "When a Q&A card crosses the drag threshold on the canvas.",
    category: "canvas",
    defaultPreset: "drag",
    defaultVolume: DEFAULT_VOLUME,
  },
  {
    id: "card-drag-drop",
    label: "Card drag drop",
    description: "When a dragged card is released after moving.",
    category: "canvas",
    defaultPreset: "drop",
    defaultVolume: DEFAULT_VOLUME,
  },
  {
    id: "artifact-drag-drop",
    label: "Artifact drag drop",
    description: "When a canvas artifact node is released after moving.",
    category: "canvas",
    defaultPreset: "drop",
    defaultVolume: DEFAULT_VOLUME,
  },
  {
    id: "canvas-pan",
    label: "Canvas pan",
    description: "While panning or zooming the canvas viewport (distance-based ticks).",
    category: "canvas",
    defaultPreset: "scroll-tick",
    defaultVolume: 0.35,
  },
  {
    id: "branch-collapse",
    label: "Branch collapse",
    description: "When a lateral branch thread is collapsed or expanded.",
    category: "branch",
    defaultPreset: "collapse",
    defaultVolume: DEFAULT_VOLUME,
  },
  {
    id: "chat-collapse",
    label: "Chat subtree collapse",
    description: "When a card's answer subtree is hidden or shown.",
    category: "branch",
    defaultPreset: "collapse",
    defaultVolume: DEFAULT_VOLUME,
  },
  {
    id: "branch-create",
    label: "Branch create",
    description: "When a new branch is created from a plug.",
    category: "branch",
    defaultPreset: "swoosh",
    defaultVolume: DEFAULT_VOLUME,
  },
  {
    id: "plug-connect",
    label: "Plug connect",
    description: "When an artifact or asset plug snaps to a composer target.",
    category: "branch",
    defaultPreset: "receive",
    defaultVolume: DEFAULT_VOLUME,
  },
  {
    id: "artifact-panel-open",
    label: "Artifact panel open",
    description: "When the artifact side panel slides in.",
    category: "artifact",
    defaultPreset: "expand",
    defaultVolume: DEFAULT_VOLUME,
  },
  {
    id: "artifact-panel-close",
    label: "Artifact panel close",
    description: "When the artifact side panel is dismissed.",
    category: "artifact",
    defaultPreset: "collapse",
    defaultVolume: DEFAULT_VOLUME,
  },
  {
    id: "artifact-focus",
    label: "Artifact focus",
    description: "When the viewport pans to highlight a canvas artifact.",
    category: "artifact",
    defaultPreset: "pop",
    defaultVolume: DEFAULT_VOLUME,
  },
  {
    id: "agent-thinking-start",
    label: "Agent thinking start",
    description: "When a card enters the thinking state.",
    category: "agent",
    defaultPreset: "tick",
    defaultVolume: DEFAULT_VOLUME,
  },
  {
    id: "agent-streaming-start",
    label: "Agent streaming start",
    description: "When the first answer token arrives.",
    category: "agent",
    defaultPreset: "keypress",
    defaultVolume: 0.6,
  },
  {
    id: "agent-complete",
    label: "Agent complete",
    description: "When the agent finishes a response.",
    category: "agent",
    defaultPreset: "success",
    defaultVolume: 0.75,
  },
  {
    id: "agent-error",
    label: "Agent error",
    description: "When an agent request fails.",
    category: "agent",
    defaultPreset: "error",
    defaultVolume: 0.75,
  },
  {
    id: "undo",
    label: "Undo",
    description: "When the user undoes a canvas edit.",
    category: "history",
    defaultPreset: "undo",
    defaultVolume: DEFAULT_VOLUME,
  },
  {
    id: "redo",
    label: "Redo",
    description: "When the user redoes a canvas edit (preview only — not wired in app).",
    category: "history",
    defaultPreset: "redo",
    defaultVolume: DEFAULT_VOLUME,
  },
];

export const SOUND_EVENT_IDS = SOUND_EVENTS.map((e) => e.id);
