/** Demo transcript for the Conversation → Flowstate playground (admin-only). */

export const HUBERMAN_NEUROPLASTICITY_TRANSCRIPT = `Welcome to Huberman Lab Essentials, where we revisit past episodes for the most potent and actionable science-based tools for mental health, physical health, and performance. My name is Andrew Huberman, and I'm a professor of neurobiology and ophthalmology at Stanford School of Medicine. Today we're talking about neuroplasticity, which is this incredible feature of our nervous system's that allows it to change in response to experience. Neuroplasticity is arguably one of the most important aspects of our biology. It holds the promise for each and all of us to think differently, to learn new things, to forget painful experiences, and to essentially adapt to anything that life brings us by becoming better.

All of us were born with a nervous system that isn't just capable of change but was designed to change. When we enter the world, our nervous system is primed for learning. The brain and nervous system of a baby is wired very crudely. Through your experience — what you were exposed to by your parents or other caretakers, through your social interactions, through your thoughts, through the languages that you learned, through the places you traveled or didn't travel — your nervous system became customized to your unique experience.

However, there are aspects of your nervous system that were designed not to be plastic. Those circuits include the ones that control your heartbeat, your breathing, and your digestion. And thank goodness those circuits were set up that way, because you want them to be extremely reliable. One of the great gifts of childhood, adolescence, and young adulthood is that we can learn through almost passive experience. And then after age 25, if we want to change those superhighways of connectivity, we have to engage in some very specific processes. Those processes are gated — you can't just decide to change your brain. You have to go through a series of steps to change your internal state in ways that will allow you to change your brain.

After puberty, the human brain and nervous system adds very few, if any, new neurons. So even though we can't add new neurons throughout our lifespan, it's clear that we can change our nervous system — that if we create the right chemical circumstances in our brain, and the right environmental circumstances around us, our nervous system will shift into a mode in which change isn't just possible, but probable.

One of the ways we can all get plasticity at any stage throughout the lifespan is through deficits and impairments in our sensory apparati — our eyes, our ears, our nose, our mouth. In individuals that are blind from birth, the occipital cortex, the visual cortex in the back, becomes overtaken by hearing. The neurons there will start to respond to sounds as well as Braille touch. Blind people who use their visual cortex for Braille reading and for hearing have much better auditory acuity and touch acuity. In fact, you will find a much greater incidence of perfect pitch in people that are blind. That tells us that the neocortex is really designed to be a map of our own individual experience.

A few years ago, a woman came up to me and said that every time I speak, it really stresses her out — my tone of voice reminded her of somebody she had a really terrible experience with. Over a two-week course, she would come back and say, "You know what? I think just by telling you that your voice was really difficult for me to listen to, it's actually becoming more tolerable to me." By the end, we became pretty good friends. What this says is that the recognition of something — whether an emotional thing or a desire to learn something — is actually the first step in neuroplasticity. When we decide to shift some behavior or bring some new piece of information into our consciousness, that awareness cues the brain that those reflexive actions are no longer fated to be reflexive. What it is, is our forebrain, in particular our prefrontal cortex, signaling the rest of our nervous system that something we're about to do, hear, feel, or experience is worth paying attention to.

One of the biggest lies that seems quite prominent right now is that every experience you have changes your brain. That's absolutely not true. The nervous system changes when certain neurochemicals are released and allow whatever neurons are active in that period to strengthen or weaken their connections. If you're older than 25, your brain will not change unless there's a selective shift in your attention or your experience that tells the brain it's time to change.

In the early '90s, a graduate student named Gregg Recanzone was in the laboratory of Mike Merzenich at UCSF. They set out to test the idea that the adult brain simply isn't plastic — and proved the opposite. A subject would sit at a table while they imaged the representation of the fingers. There was a spinning drum with little bumps, some spaced close together, some far apart, and subjects had to press a lever whenever the spacing changed. As people paid more and more attention to the distance between the bumps, there were very rapid changes — plasticity — in the representation of the fingers. In control experiments, subjects touched the same bumps but paid attention to an auditory tone instead. Then there was plasticity in the auditory portion of the brain, but not the touch portion. The experiences that you pay super careful attention to are what open up plasticity, and it opens up plasticity to that specific experience.

So the question is why. The first neurochemical is epinephrine, also adrenaline — we call it adrenaline when it's released from the adrenal glands, epinephrine in the brain, but they're chemically identical. Epinephrine is released from a region in the brainstem called locus coeruleus, and it equates to alertness. But the most important thing for getting plasticity is that there be epinephrine plus the release of the neuromodulator acetylcholine. Acetylcholine from the brainstem acts as a spotlight — it raises signal to noise so one particular input comes through. But those two things alone are not enough. There needs to be a third component: acetylcholine released from an area of the forebrain called nucleus basalis — nucleus basalis of Meynert. If you have acetylcholine released from the brainstem, acetylcholine released from nucleus basalis, and epinephrine, you can change your brain. Not only will the nervous system change, it has to change.

Now let's translate this into protocols. We know we need epinephrine — that means alertness. Most people accomplish this through a cup of coffee and a good night's sleep, so you should master your sleep schedule. Beyond that, people use accountability: they tell others what they're going to do, or post a commitment publicly, or write checks to organizations they hate. Or they do it out of love — running a marathon or learning a language for somebody they care about. From the standpoint of epinephrine, it doesn't matter — your brain does not distinguish between doing things out of love or hate, anger or fear. All of them promote autonomic arousal and the release of epinephrine. So identify a kit of reasons, several reasons, fear-based and love-based, to ensure alertness, energy, and attention for the task.

That brings us to attention. People ask what they can take to increase acetylcholine. Nicotine binds to the nicotinic receptor, which is involved in attention and alertness — I have a Nobel Prize–winning colleague who chews Nicorette while he works. But if you go that route, be careful how much you rely on it, because the essence of plasticity is to create a window of attention distinct from the rest of your day. The best way to get better at focusing is to use the mechanisms of focus you were born with. The key principle is that mental focus follows visual focus. When we move our eyes slightly inward toward a particular visual target, our visual world shrinks, and we activate a set of neurons in our brainstem that trigger the release of norepinephrine, epinephrine, and acetylcholine at the relevant sites for plasticity. Spending just 60 to 120 seconds focusing your visual attention on a small window of your screen increases not just visual acuity but activity in brain areas that gather information from that location. So if you want to improve your ability to focus, practice visual focus. For low-vision or no-vision folks — and for learning that relates to sounds — closing the eyes creates a cone of auditory attention instead.

Once you get the epinephrine and the acetylcholine and can focus your attention, the question is for how long. Ultradian cycles last about 90 minutes, and the typical learning bout should be about 90 minutes, including a 5-to-10-minute warm-up where you give yourself permission not to be fully focused. That means eliminating distractions — turning off the Wi-Fi, putting your phone in the other room. Attention drifts, but we have to re-anchor it, and the way to do that, if you're sighted, is with your eyes.

But the real secret is that neuroplasticity doesn't occur during wakefulness — it occurs during sleep. If you focus very hard on something for about 90 minutes, that night and the following nights while you sleep, the neural circuits highlighted with acetylcholine transmission will strengthen, and others will be lost. There's a stamp in the brain where acetylcholine was released that marks those synapses so they're more biased to change. You can also partially bypass the need for deep sleep with non-sleep deep rest, these NSDR protocols. A paper in Cell Reports showed that a 20-minute NSDR protocol or a shallow nap taken immediately after a difficult spatial-memory task produced significantly higher rates of learning than a good night's sleep alone.

To synthesize: plasticity occurs throughout the lifespan, but as an adult you have to be alert — know when in your 24-hour cycle you're most alert and protect that time. Increase acetylcholine through the visual system, practicing how long you can maintain visual focus on a target. Ask whether you're trying to focus too much for too long — very high-performing people are not focused all day; they take walks and let the mind drift. We learn best in 90-minute ultradian bouts, and deliberate disengagement afterward — plus deep sleep — accelerates the rate of plasticity. Thank you for your interest in science.`;

export const HUBERMAN_NEUROPLASTICITY_SOURCE_URL = "https://www.hubermanlab.com";
