/** Demo transcript for the Conversation → Flowstate playground (admin-only). */

export const JAGADAMBA_THEATRE_VIDEO_URL =
  "https://www.youtube.com/watch?v=mP94mZ5RxEU";

/**
 * Derived chapters — this description carries no timestamp list, so YouTube
 * shows no chapter markers and there is nothing to lift verbatim. Cut by the
 * five-signal rule (fresh question + new cast fire together at every boundary
 * below), then merged down.
 *
 * The runtime formula targets three chapters for a 34-minute episode; this
 * lands on six. The binding constraint here is the per-chapter budget rather
 * than the target: the transcript yields ~22 primary artifacts, and four
 * chapters' worth of cap would mean discarding half of them. Nothing further
 * merges without joining unrelated casts — the Bombay distributor offices and
 * the fans going over the compound wall share no people, no place and no
 * question. Titles are claims, per the derived-chapter rule.
 */
export const JAGADAMBA_THEATRE_CHAPTERS: {
  start: string;
  end: string;
  title: string;
}[] = [
  {
    start: "1:53",
    end: "7:43",
    title: "He saw Sapphire in Chennai and set out to better it",
  },
  {
    start: "7:43",
    end: "10:35",
    title: "Every three months they went to Bombay to buy the films",
  },
  { start: "10:35", end: "14:15", title: "He wanted to be the first in India" },
  {
    start: "14:15",
    end: "21:35",
    title: "Action played, comedy died, and the fans went over the wall",
  },
  {
    start: "21:35",
    end: "25:54",
    title: "Play safe — and everybody grows together",
  },
  {
    start: "25:54",
    end: "33:44",
    title: "He still changes the speakers himself",
  },
];

/*
 * Auto-generated (ASR) captions, timestamps stripped. Two speakers — Vishnu
 * hosting Rooted Stories, Mr. Jagadish of Jagadamba Theatre answering — but the
 * captions carry no speaker labels, so attribution on any extracted artifact is
 * read from the turn structure and only asserted where that structure is
 * unambiguous.
 *
 * Disfluencies, filler and mangled proper nouns are left exactly as the machine
 * produced them. The recurring ones, for readers of the builder: "Jagda" /
 * "Jagdamba" / "Jagamu" / "Jakda" are Jagadamba; "Visak" / "Wisag" / "Shakat" /
 * "Isaac" are Visakhapatnam; "safari theatre" and "Sapphire" are Chennai's
 * Safire; "sense of sound" and "sensor sound" are Sensurround; "cholelay" and
 * "Cholay" are Sholay; "Leila Mahal" is Leela Mahal; "liner speakers" are line
 * array speakers; "the only seven theater" is the only 70 mm theatre. Cleaning
 * any of it up would make every quote unverifiable against the source.
 *
 * The first minute is a cold-open montage assembled from lines that recur later
 * in the interview, so nothing is extracted from it — the second occurrence is
 * where each line actually sits.
 */
export const JAGADAMBA_THEATRE_TRANSCRIPT = `1 2 Sorry. [clears throat] [laughter] Oh yeah, we'll take a better start. Jagd Damba to me has has a lot of memories. So you tell me what is your first memory of Jagdamba? Before Jagda opened itself when back then if you got English movies. So it was a totally a different experience for the wife. Which was the biggest blockbuster? The longest playing [music] the Telu film was Was there any period of time which was very difficult? Those comedy movies they used to play for 50 weeks over there. Which is a blockbuster that fans celebrated. Celebrating crazy fans and

Hello guys welcome to rooted stories. I started rooted with one vision to tell stories about wis people from brands and institutions from Wise which have made it big. Today I'm having a conversation with someone I've known for a very long time. He happens to run one of the most iconic legacy theaters of Vishaga Patnam Jagadamba Theater. The Jagadamba Theater has been an integral part of Visak's identity and I'm lucky to have my first conversation with him. So welcome. Thank you Isho. Don't I mean I'm not going to keep it formble the way I solved it but we're going to have a very casual conversation. Yeah. Yeah. And because uh this is my first podcast and I'm so glad you are sitting with me and we are having this conversations.

Jagda to me has has a lot of memories. I think I've told you this before also but I'm going to tell this again that my first ever memory of a Hollywood film I think was Godzilla in 1998. Uh 1988. 1988. No, no, the 199 uh or Jurassic Park. Uh Jurassic Park. Jurassic Park. Yes, I got it wrong. Jurassic Park. And since then, I've had insane love for uh dinosaurs. That's the kind of experience that 70 mm uh Dolby effects had on me. Yes. So I have I always was curious to know so much more about Jagdamba because the brand is so legendary that they named a whole junction after it. So you tell me what is your first memory of Jagdamba?

My first memory of Jakda is uh before Jagda opened itself when the screen was ready we were sitting in the theater to see some projection. Okay. I was maybe 8 years or something at that time. Right. So the we already had a theater by that time Ramak Krishna 3M theater. Then in 1964 when we went to Chennai my father me and my mother we went to this Sapphire theater newly opened with Cleopatra movie. Okay. Wow. uh just my my father opened in 1960 the Ram Krishna theater and now he wants to open another theater because after seeing sapphire in Chennai he wanted to give that experience to Shakat now he wants to better that experience okay so since then he started hunting for a site and ultimately in ' 68 he bought the site okay and in 1970 he opened the theater wow

at that point was the was Jagdlamba center a main area or was it just barren land and was it easy to build something there? It was a barren land because it it needed a bigger uh space, right? Because he he had the concept of building a theater along with shopping complex and everything. Okay. Wow. That was the first in India, right? There were no malls and multiplexes at that time. Wow. Okay. So, he planned a theater along with shopping mall and uh including a hotel, lodging, everything. Wow. Integrated building. So it even had a hotel, okay, with the rooms and all. 23 rooms and all. Wow. Okay. And a number of uh uh shops, number of shops down below and a movie theater. Okay. That was a concept. He entertained himself and made it wonderful. He bought the site in ' 68. In 18 months, he finished the job. Okay. Wow. 18 months he opened the theater.

Was it easy for him to raise funds and uh start a theater at that point? How was it starting a theater back then? Yeah. Uh raising funds was uh tough only, right? Because it was a huge investment, right? By that time we already had Ram Krishna Theater and we were doing some other businesses. Okay. But that was not enough to make this theater. So we so we took uh took no banks banks and all that and did the whole thing. Wonderful. How old were you then? I was 8 years. Eight.

So since then you were introduced to the industry of theaters exhibitors. Since uh yeah when I was eight only my father was taking me to the theater complex right when it was being made. Okay. So they were constructing the theater and I was watching the construction and I told my father let's have our house also in here also because you wanted to be I wanted to watch movies also. [laughter] cuz I wanted to watch movies all day. Right. But that one one thing he never entertained [laughter] being a man who is an exhibitor and he's a owner of a theater. He didn't let you watch movies sir. Uhhuh. No. No. He he let me watch movies but not have a house over there. Okay. Okay. Okay. That was obviously too much to ask.

Wonderful. [snorts] What was the first movie in Jagamu? Where Eagles There. Sorry. Where where eagles. Oh, wonderful. Yeah. Okay. Richard Burton, Clint Eastwood, Mary was a starring that is a nice 71 theater experience. The movie was a great experience. Right. People of Vishakapa had a blast. Wonderful watching that movie. I read somewhere that because when Ram Krishna Theater was there uh Ramavgaru he wanted uh to make get English movies to Vishakapatnam. He made Jagama. Is that true? Actually that he was always trying to play English movies in Ram Krishna theater also. Okay. But then when he once he watched in ' 64 this safari theater because of 70mm format made a huge difference. Right. So he he wanted to bring that format here. Okay. To vishaka people. Wonderful. So it was a totally a different experience for the visak people. Right. It was a total experience. Wonderful. How was Visak back then? Sorry. How was Visak back then? Yeah, it was very small place like like uh a big village. Maybe [laughter] big village was but back then if you got English movies I mean they they people were there. There was market back then also people used to come see English movies. Yes. Yes. Yes. Right. when we opened lot of English audience were there. Okay. Wonderful. I had good uh good uh audience right elite audience good audience

amazing so you were 8 years old when Jagamba started. So how was your childhood? Childhood uh tell us a little bit about your childhood. I don't think a lot of people know about that. Yeah. Uh I would like to go to the theater all the time. Every day I would like to go over there right watch movies over and over [laughter] over [snorts] and over was kind of movie fanatic only. Okay. So all these Hollywood movies no they made a big impact on my on me right the visually something and very thoughtprovoking right so it was a great experience it was nice way to grow up I guess good exposure at that age international exposure comes with the Hollywood movies and with the great uh movie going experience wonderful

So you at what age did you start working for the theater? I mean were you have did you have a work before that? Like no no uh since when I was 12 years and all I used to go along with my father to the foreign companies in Mumbai and all. Mhm. All the companies over there. These are distributors. Yeah. Distributors. Warner Brothers all these guys. Okay. Wow. 20th CS Colombia. Right. All the offices. We would go every 3 4 months to Mumbai. And we used to watch previews and all. Okay. Previews. And we used to watch some movies in there. Movies in there. And then uh we would choose our movies, make contracts and come to Isaac and play play those movies. Okay. And every 3 4 months again we would go for a new uh project. Yeah. So Mumbai also had lot of uh Hollywood movie playing theaters. Which theater in Mumbai was famous for? Like we have Jagdam here which only played English movies at one point. Jagdam always had English movies. Like Mumbai also had a theater which only played English movies. Most of Yeah. Bombay had several. Okay. Like Regal. Okay. Uh theaters like that. Regal cinema. Uh Regalos. Okay. Metro. Metro is also there. Okay. Metro. Yeah. Sterling was Tatas theater tatas. Was it expensive to get English movies to India back then? No. No. It's like I mean like were they more expensive than Indian films or were they at par? Uh at par only. We used to play them and share sharing bases. Okay. They needed a theater and ours is the only seven theater at that time in Andhra Pradesh. Wonderful.

Yeah. So whose influence did you have while growing up? Your mother's or father's most like my father. Yeah. Yeah. He was innovating. No. Right. He was innovating great uh picture and sound systems and uh uh if a new sound system would come uh unlike sense of sound he introduced it then. Okay. Then we opened it uh with that cholelay movie. Okay. Wow. Cholay, right? Yeah, 70 mm with sensor sound. Okay. It uh surely was normally that uh 70 mm six track stereophonic sound but we added sensor sound to that. Okay. What what is can can you like elaborate on that? Like uh uh the experience was very good actually. Okay. When something is thrown around it would seem like something is really thrown around. So it's going around you. Going around you more realistically. Okay. Okay. Wow. Did you have a feeling? Actually Leila Mahal played the first version of Sho. Okay. Yeah, they played for 100 days and then we played the uh sound table version along with sensor sound. Okay. And we played it for 50 days. Wonderful. Wow. With more revenue. Okay. Okay. More revenue. Wow. People came back for the experience. That sound experience. Yeah. The whole experience. Lovely.

The screen experience and the sound experience actually. But it was manually operated. Okay. Manually operated. So somebody had to be there when that sound is. Yeah. The operator will have to operate. Okay. Okay. Since uh thing and operate, right? And I used to have fun after going after my college. I used to go and uh operate [laughter] myself. Wow. During that evening show and uh part of night show, right? Cuz I had no I was somehow you know felt like doing that. Wow. Very cool. I wanted to give audience a great experience cuz I thought my operator was not doing a great job. I thought I should better. [laughter] So, [clears throat] so you got good at it. Yeah, I got good at it. So, I started uh you know studying speakers and everything and then when once new speakers and all would come, I would change these speakers. Okay. Wow. Upgrade to the next versions.

Right. How would you study the information about this back then when there was no internet and all? How how how would you consume this data? Like would you read magazines or how was back then? How was it? Absolutely. Like sound design magazine and all used to be Yeah. Okay. And in the end of the Hollywood movies uh they you know format used to come Dolby stereo and all that. Right. Okay. Okay. Yeah. At that time you used to have only 70 mm and four track stage. Right. And I used to wonder what this Dolby studio is all about. Okay. Wow. What is this Dolby studio all about? So I I even went to you know Prasad for Prasad lab. Okay. And inquired with him about the sound system. Okay. Dolby. Then he got me a quote from UK. Okay. Okay. So that is how I started thinking about Dolby. Right. And uh we ordered the equipment and uh I went in uh ' 92 to England to actually see what Dolby sound is all about.

Was it like the first theater, the only theater at that point which had this kind of uh sound system? Did anybody try copy it? Uh it was it became the third one. Okay. The first was uh Delhi Priya and Mumbai Sterling. So Delhi, Mumbai and then we and then we wow cool. South India we are the first. Right. Right. Wonderful. Actually I wanted to be the first one. Okay. You wanted to be the first in India. The first in India. I wanted to be the first in India. Right. Did you ever think of doing any other business? Were you so invested in the theater business? Because you're the way you're telling me you're really invested in the sound detailing the screen. So did you ever think of doing any other business or were you always into this? Uh always into this. Right. Always. From age 8 you have been a theater [laughter] glued.

Wonderful. There is a statue outside Jagdamba which is like a disc throwing. Yeah. What is that about? And my father is very fond of all these athletes and all. Okay. A Greek uh discuss disc thrower. Okay. Okay. Had one in Ram Krishna theater also. Okay. An athletic statue somebody [clears throat] is a fighting guard with a sword. Oh sweet. way back in 1960. Okay, this is 1970 and with the discus. I was also an athlete at one time. Used to throw zins and wow discus and short puts and all that.

So sir uh after jagdamba started was there any period of time which was uh very difficult any challenges that uh Rambgaru or you had to face was there any moment like that where you had to overcome some challenges? Uh not really much so many uh initially anti Hollywood movies were not so hot in my hand. Okay. They were good but the occupancies used to vary. Okay. Action movies used to do well but comedy movies never used to do well. Okay. Uh we used to watch movies in Mumbai. Those comedy movies they used to play for 50 weeks over there. Okay. And we would have high hopes in my eye. Okay. And it would not even play for 2 3 days. Okay. Okay. Wow. So that was the difference right only action movies. Okay. Action movies from Terminator only action [laughter] cinema audience itself they strive on action. Action movies action heroes. No comedy movies.

Right. I know you met Jackie Chan. Yeah. So tell us about that experience. Yeah, when I went to Singapore, I met Jackie Chan, right? We had this senior Asia convention. So we were meeting some actors and uh some big film distributors. Okay. Some producers at that time Titanic was also you know we had a play or not right worldwide. We had a show. Right. Right. At that time I met Jackie Chan. Wonderful. cuz I was also a martial artist because of End of the Dragon. That movie inspired you to get into martial arts. Wonderful. It inspired me to do some martial arts at that age. And did you pursue martial arts for a while? Yeah. Yeah. I was a black belt. Wow. Wonderful. Wow. We didn't know this. Yeah. [laughter] So, when did you like last practice martial arts? From 15. I used to uh I started martial arts. Okay. Cuz I saw Ender of the Dragon when I was 15. I was doing my metriculation right we went to Mumbai and uh theater was playing uh end of the dragon. Mhm. But uh I was not allowed because it's uh over 18 years. Okay. So I we had to call the film to we [clears throat] had to know exhibitor to allow us right it was yeah under circumstances. [laughter] violence because of violence. Because of violence. Yeah. That movie changed me.

Which was the biggest blockbuster English movie uh in that played in Jagamba the Jurassic Park. Jurassic Park. The first one. Yeah. 10 weeks we played. The longest play in the Telugu film was Shiva. Shiva. Shiva. Oh. How many days did it play? 155 days. Wow. We had to terminate because of the next film. Okay. Donga challenging movie. Okay. We had to terminate on 155 days otherwise it would have gone longer. Right. That was also one crazy movie. Yeah. After it inspired our generation. Made a chala big difference. Right. Ram Gopala has made a difference. Right. So which is the biggest your Shiva is the biggest blockbuster according to you.

Yeah. So which is a blockbuster that fans celebrated like fans went crazy with decorating and like just celebrating which movie was that movie celebrating crazy which movie of his was like the for example used to be 6 ft after playing Movies we raise the wall [laughter] uh general bip and then they used to jump over the wall. Okay. Jump over the wall and come. Okay. And then we raise the wall to 10 ft. Every movie.

What is your craziest fan experience like any interaction with the fan? Did anything like that? Uh, I don't think so. But did you have any crazy experience with a fan? Fan? Yeah. With a fans association or one fan who wants tickets or something personally fans. Okay. So the whole family. Okay. Like so all those fans are very friendly with me. did anything like that. Has it changed over time? Like before how fans used to behave to now has it changed or has it been? They're more sensible now. Okay. Way back I think they used to be a little uh erratic. Okay. But nowadays fans are more sensible. Okay. Because they know fans actually [snorts] heroes are all together over there [laughter] out there. So those fan wars are not in they also know they're together. Why why can't we be like that? Right. Fair enough.

I keep seeing because because of these re-releases some theater owners are complaining that they've broken our seats or until papers somebody lit it up things like that are not have reduced from before or they they still happen have they happened in Jango? No no no uh actually initially we used to screen those movies now we stopped screening them. Okay. and they'll be standing on the seats, jumping on the seats. Then how do you recover from that? You just have to repair those seats or chain those seats and [laughter]

so which was the biggest disaster like I mean some movie that you probably lost money or more than that maybe you just thought it's going to do very well but it didn't do well. Is there any film that it happens with some movies right? Can't help it. Okay. So, it's part of the business. Part of the business, right? But any such movie that you remember that you had hopes, something that you passionately picked up but it didn't work. Uh I would know because I didn't lose money because I would change the movie next week. Okay. Okay. So, I play safe.

Okay. So, for people who don't know theater business, can you explain how it works? So, I I know that there's a producer who produces a film. There's a distributor who distributes it amongst theater exhibitors and then you are an exhibitor, right? But how does the business work? How does one make money owning a theater? Movie has had to go you can make money but how like how do you so you you pay the distributor or the distributor pays you? How does that equation work? Or are you relate are you directly work going to work with the producer? How does the chain of business? the producer distributor buys it from the producer. Okay. And we just pay advance to the distributor or if the there's no distributor, we pay the producer. We we don't risk matter. Okay. We just play give advance on move up then next movie is coming. Okay. But we don't uh gamble like it happens in some places where they'll give a minimum guarantee, share guarantee. Okay. And they'll lose if the movie flops. Okay. They'll recover, right? They'll be good. Visak people are more uh sane, I guess. So all the theater owners in Visak play safe. Oh, I play safe. They are very sane people. [laughter] You have good relationship with other theater. Yeah. Yeah. Yeah. We have our meets and all. Okay. So you guys have a little association of people and very nice maybe parties. Okay. So there's no sense of that competition. Nothing nothing. That's one thing about I think if you grow you grow everybody grows together. Everybody grows together. [laughter] That's wonderful. And we [clears throat] share we interact.

So how did multiplexes affect single theaters? Like when multiplexes started I think in Wisag it started with Vun Inox. Yeah. And then CMR Central had Inox 2. M. So [clears throat] did it affect your business in any way? That has its own sense of business. Yeah, actually our single screens are doing better than multiplexes. Right. The other day one producer was saying it all these single screens. J Dumba, Melody, Saratam, they're doing better than multiplex and he was telling her okay during CO they say that I mean during co a lot of single screens were affected. Multiplexes still had backing and all. Is that true or nothing? Nothing like that. It was happening for both of us. Okay. Both of us. But what kind of impact did it have on you on the Jagda theater? Jagda theater did not have much impact. Okay. Much impact. We were playing previously four weeks on now we are playing only two weeks. Okay. But we are getting our flow of movies. Right. Previously four weeks are there. 3 weeks flow movies we could not play. Okay. Now we are able to play a little more. Okay. But because of that the OTT wave happened but did that make any impact? Uh maybe to the theaters uh few theaters right? Not for uh Jagda. Okay. It still has a fan base. I think by the time this podcast comes out Odyssey would have been in theaters. People are dying to watch it. Yeah. Jagda has its own experience. Even if any movie people just come for Jig Zamba the experience. For the experience. The onions popcorn. They [clears throat] want to go there and watch movie for the experience. And you also made really good seats. I'm always very comfortable in Jaguar. Okay. Thank you. So what is what are the seats? Are they like did you get it customized or Yeah, customized. We had them made like okay made them. They're pretty luxurious. Yeah, because I'm a big guy so I can customize it to myself. [laughter] But obviously it'll be great. Everybody is benefited now. Everyone is benefited.

If a young entrepreneur wants to start a theater, what would your suggestion be? If I want to start a movie theater, a single screen, make a nice theater with big screen, great sound, and you'll you can serve the public around your theater, right? And then do I add anything like you used you had a gaming zone first ever gaming zone of vishaka. Yeah. You had bikes and cars and all of those. Yes. Yes. What should I not do? Don't make a small theater. [laughter] Uncomfortable seating. Right. That's all. So tell me who is your favorite hero? Chiranji in Telugu. Amitab in Hindi. Okay. And Hollywood stars Chalaman. [snorts] I can't say this lie.

Okay. Did you ever host a 100 day function something like that in the theater? Yeah. Yeah. Fans celebrate we cut cakes and do all that. Okay. Did you celebrate with him? Yeah. Yeah. [clears throat] Which movie was that? Okay. Oh, back then. Back then recently. I think even Shankar the MBS did really well in Jagdan. We did not play that. Zindabad. I think one of the I think the second part uh was celebrated. I remember that bit. I was here in Wisagh at that point. It was celebrated like Shankarabad was a big thing in the part two. No, normally for all children movies all the any movie whatever uh the movies we celebrate days I think 100 days revenues we are getting faster

right are you making any changes or adding anything to the theater we keep on doing behind the screen all the speakers and everything okay whenever new speaker comes with the greater frequency or a nicer frequency. I change it. I can't stop myself. Okay. Right. I can't stop myself. Wonderful. Now we [clears throat] made uh very we have very good speakers now. Very good speakers. Okay. So the dynamic range of uh the sound frequencies is wonderful and matter. Okay. And we have the liner speakers. Okay. We are the first one in India to put line speakers behind the screen. Okay. name Janet Jackson show us I went to our music and shows and okay there I experienced these liner speakers so I wanted those speakers and we kept those speakers in Jaya especially sound is changing a lot right now Atmos with its uh dynamic sound waves and all sounding very good in the theaters okay So experience is totally different now from what it used to be. Okay. And I do sound equalization myself. Okay. Yeah. Dolby equalization. Mhm. I do it myself. Theater equalization. Right. I learned it uh from my engineers and improvised it on that. Wow. That is so cool. You're so involved in uh running the theater. I went to Dolby Labs. Wonderful. to enquire with them how better to do on that.

So these days uh Vonasi and Odyssey they're all coming in IMAX screen scale. Yes. So and they're saying that future is the IMAX experience. What would you say about it? And are you planning to take Jagadamba to the IMAX level at some point? Jagamba originally started as a 70 mm theater with the 70 mm film. The same film IMAX is using Odyssey is made with that film only. Okay. So, we started off with that film only. Okay. Okay. Wow. And with six tracks stereo for example and it's huge screen, right? Huge screen. 70 mm. It's uh better than all these 4K 8K. Maybe it's up to 32K. Okay. They say, right? So 70 means that see the IMAX experience itself is the 70 mm uh uh 70 mm [clears throat] experience. But uh IMAX uses bigger screens, bigger screens and more format uh space. Okay. On the 70 mm film.

So you know Visak is growing at a rapid pace right now. Google data centers coming now. You see so many tech companies coming. Yes. And what would you do like what is your upgradation plan? M are [clears throat] you planning to upgrade it or are you planning to stick to how you're doing it like slow like you're changing the sound, you're changing the screen experience or are you planning to put in sudden investment and just make it uh push it like are you aggressive about upgrading? We keep on upgrading right but when you come and see at Jagda you'll experience automatically correct and you're coming back to it because of the experience you seem to be coming back is that why you don't uh like stress too much about marketing and digital marketing because inox and all are very heavy on digital market any multiplex brand jagd a brand you've always believed in word of mouth or have you invested in digital marketing and any kind of branding front. You know, we always uh relied on word of mouth, right? That's it. People will go and experience it and digital marketing. When you go there and you don't experience it, you're not going to believe it.

Now, I'm going to ask you some rapid fire questions. Okay. Okay. Tea or coffee? Used to be coffee, now it's tea. Okay. [laughter] Mountains or beaches? Uh, beaches. Beaches. Are you a morning person or a night person? Night person. I already asked your favorite hero. Who's your favorite heroine? Heroine. Heroine. So many changing. [laughter] They keep changing. Okay. One one name if you have to say [sighs] uh when I was 8 years 9 years Mary in a village there. Okay. First blonde girl I Wow. I lost it for a long time. [laughter] Okay. So I kind of liked her. Okay. So first crush was her on the wonderful favorite movie of all time. It's difficult but I understand one movie end of the dragon. Enter the dragon. Okay. What is your most favorite spot in wis even now? I guess it keeps changing but uh so it keeps lingering right. We are called rooted for a reason that that I'm back to my roots which is wise. Yes. And the idea is to be rooted is to know more about my roots people from my roots and brands and institutions from my roots. So what is your most rooted moment? For me it's Jdamal kind of the theater rooted. Yeah. Right. Rooted and growing. Okay. still growing.

Thank you so much for sitting with me and having this conversation. You're most welcome. I hope we can do this one more time and I can ask you way more questions. But thank you so much for doing this. This is really special for me because this is my first episode of Rooted Stories and uh yes, I can't wait to You did well Vishnu. [laughter] Thank you so much. Thank you. So guys, that was me having a conversation with Mr. Jagish the man the proprietor the showrunner of Jagadamba theaters. Uh please do subscribe and thank you for watching it till the end. I hope to see you with another story with another legendary brand. This is my rooted moment happening right here. Thank you.`;
