/** Demo transcript for the Conversation → Flowstate playground (admin-only). */

export const PRASHANT_KISHOR_VIDEO_URL =
  "https://www.youtube.com/watch?v=fPP_3XCXbPQ";

export const PRASHANT_KISHOR_CHANNEL_URL =
  "https://www.youtube.com/@UNFILTEREDbySamdish";

/**
 * The nine chapters this canvas groups the podcast into — a curated spine over
 * the source's own fifty-odd auto-generated navigation points (see the raw
 * "Chapter N: to ..." markers), grouped by theme rather than kept one-to-one.
 * `start` is read off the source's own timestamps for the lead topic in each
 * group.
 */
export const PRASHANT_KISHOR_CHAPTERS: {
  start: string;
  end: string;
  title: string;
}[] = [
  { start: "1:23", end: "5:59", title: "Introduction" },
  { start: "5:59", end: "10:22", title: "PK's Mission" },
  { start: "10:22", end: "14:26", title: "Speeches and Messaging" },
  { start: "14:26", end: "19:39", title: "Who is Funding the Yatra" },
  { start: "19:39", end: "24:22", title: "Nitish Kumar, Democracy, Ideologies" },
  { start: "24:22", end: "32:33", title: "Family Time and Workaholic PK" },
  { start: "32:33", end: "38:25", title: "How to Win Elections in India" },
  { start: "38:25", end: "44:19", title: "Realities of Bihar" },
  { start: "44:19", end: "1:08:10", title: "Modi and BJP's Ideology" },
];

/*
 * Auto-generated (ASR) captions, timestamps stripped. Two speakers — Samdish
 * interviewing Prashant Kishor during a day on Jan Suraaj's Padyatra in
 * Begusarai, Bihar — but ASR carries no speaker labels, so attribution on any
 * extracted artifact is read from the turn structure and is only asserted
 * where that structure is unambiguous.
 *
 * Disfluencies, filler, on-screen hashtags and mangled fragments are left
 * exactly as the machine produced them. Cleaning them up would make every
 * quote unverifiable against the source.
 */
export const PRASHANT_KISHOR_INTERVIEW_TRANSCRIPT = `Should I ask a personal probing question or an easy one? Ask whatever you want. I've never directed anyone to ask me a particular question in my life. Do you dance? What's on your screen saver? Aamir Khan or Salman Khan? I don't think there would be romance in your life. In normal life, people say, he's my friend, he's my neighbour. I don't have anyone. So, the more stress I have, the better I feel. Have you ever thought of taking therapy? Or do you? Huh? How rich are you? How much are your shoes for? How much money? Indian National Rupees. Who's funding the yatra? It might be Rahul Gandhi doing it. I'm sure Captain sir must have served you champagne. I have never posted on Facebook in my life. People think I'm a social media wizard. People compare Mamata Banerjee and Narendra Modi in terms of their dictatorial tendencies. Let's stop this now. Give me five minutes. No, no. Let me leave. Give me five minutes. How do you win elections in India? I helped Nitish Kumar in 2014, 2015 elections in Bihar. And people abuse me. I mean, you were with Modi ji in two elections. I used to live with him in the same house. In the same house? Yes Do you think you're more powerful than Amit ji? PK is the game changer. Prashant Kishor was the one who helped win elections. I am Prashant Kishor. Prashant Kishor Prashant Kishor My name is Samdish. The world is in love with me. My looks. My physique. You've said it. I'm always candid when I do interviews. I can see the truth in your eyes.

Those who know, know. But those who don't know... Bihar - a state in the eastern region of India, which in the Human Development Index If we compare it, it's the lowest ranked state in India. That's first thing, Bihar. Second is Prashant Kishor. After 2014, the Indian National politics, which has been in toss and turns, in that a superstar has emerged, a highly important person, his name is Prashant Kishor. He himself doesn't fight elections, he hasn't fought yet. But he has been very good at making others win. Third, Padyatra. The journey that one does on foot to deliver his message to the people, Think Gandhi, that is called Padyatra. So, today, all day, in this Begusarai district of Bihar, we will see a day in Prashant Kishor's Jan Suraaj's Padyatra! The Padyatra has been going on for a long time, but today we will spend a day. This is Begusarai, Channel is Unfiltered by Samdish. If you haven't subscribed yet, please do. And watch, it's going to be a fun day. We'll show you what we saw.

The leader of Jan Suraaj Padyatra, Honorable Prashant Kishor. has been walking in Bihar since the last 16 months. Today, he has reached your village to hear about the problems of your village. and to tell you how you can get out of poverty and how your child's education and employment would be possible in your village. Prashant Kishor ji has come to talk on these issues. My name is Prashant Kishor. I am not a politician. I am not a MLA, MP or minister. I am not even the Mukhiya or Sarpanch. I am no guide, angel, saint or beggar. I am a son of a simple family from Bihar. People say that the one whom we advise, the one whom we hold hands with, that person becomes a king by winning. If God has given me that strength and intelligence, then I have helped the leaders and the parties a lot. Once I should go and pay off my debt of soil in Bihar, by holding hands of the people like you. Give advice to you people To make a difference in your life and so that your kids can win Which is why I started this campaign Once raise your hands to give me your blessings And tell me if this should be attempted. Raise your hands to tell me if this should be attempted or not This attempt to make Bihar better, should it be done or not? Jai Bihar! Jai Bihar! Thank you very much!

#Hein We forced you to change your plan. #LordSamdish Oh, you're in such a hurry? Mic, Bhavesh bhai. Hello. This is Bhavesh. This is Prashant. I am Samdish. Where are you from? Delhi. Will you sit on the gamcha (towel), on ground? Should I spread the gamcha (towel), will you sit on it? Should I move the chair? No, not here. It will raise curiosity! What will happen? People will start getting curious. What is curiosity? curiosity means... Why is this happening? People are sitting here. So, they will think why are they sitting on the ground? It will look like a drama. Oh, is it? Maybe our audience will also think that a drama is going on. Shall we start? This is the start. #NoCap I will take an hour. I won't be able to do this for an hour. You can do it for 20-25 minutes. Then you will do it on the way. I will tell you to record this. Then you can do it where we finish. I take 2 hours of people. No, take 2 hours. No problem. I will take it. No, no problem. You can sit there in the evening and do it for an hour. No problem. So we'll do it well in the evening. Let's go. This is the start. #WeRolling Do you know the name of the channel? Unfiltered by Samdish. No, I don't know. Have you ever seen the channel? Never. I've heard about you but never seen the channel. My name is Samdish. The name of the channel is Unfiltered by Samdish. And we have come here to interview you. What are you trying to do, Prashant? What is this?

Look, when I worked at The United Nations 10 years ago, Then I came here for 10 years and did the work, that the people here named... Political consultant , political strategist All that 20 years of experience that I had, I have gathered that experience and put it together in Bihar, which is the poorest and most backward state in the country. I have put this project in a frame based on my experience of how this state can be transformed. I don't think this is a change due to the fact that in Bihar, no matter how many problems there are, you will see so many people sitting here, they will talk about all kinds of problems. That we don't have education, we don't have employment, we don't have water, we don't have drains, we don't have houses, there is corruption. But the problem is that when they go to vote, the majority of them will leave these issues and vote for caste, religion. But do they know that they can get a better life than this? Somewhere. Are they aware that it is their democratic right to have it? Look, there is awareness that it should be better. Okay. They can get it. When society underperforms for a long time, on the developmental parameter, so people's expectations have been brought to the same level. That's right. And the politicians who have been doing politics by taking advantage of that, they take advantage of that. I'm sure you can't compare it to other protest movements that have happened recently.

But say for instance, farmers protest or say NRC protest, that messaging goes to the last person, that looks very impossible in any movement. So as the leader of this, how do you make sure that that... First of all, this is not a movement. If you study the history of human civilization, I think that if you leave French Revolution as an exceptional case, then no revolution or movement has benefitted human civilisation in the long run. A revolution and movement is like a sharp weapon. If you have a sharp weapon, you can cut a big tree. But no matter how sharp the weapon is, you cannot turn a plant into a tree. The thing about creation, it is a long process of awakening of the people/society. Once it is awakened, it can lead to a movement. When Gandhi came, he didn't say, fight the British, free the country. He said, first banish the caste system, make your own clothes, clean your own latrine, be self-sufficient, speak the truth, don't do wrong. So, the character building of the society, he focused a lot on that. So, you will see this now, when I speak here, I don't give a speech, I do the question-answers. And you can't feel it on camera, you will see it in front of you. And I ask, put your hand on your child's head and say, have you ever voted for education? And so far, not a single person in Bihar has said that he has voted for education. But hundreds of people say that schooling is bad, education should be improved. So my job is to tell them how to improve. If you have this problem, you will have to vote for it. In Bihar, a person does not want to improve. A person is living a life of five years in hell. Wherever you go, we have been roaming for 17 months. We have gone to 4,500 villages. Wherever you go, people are crying. Hey brother, there's no education here. Hey brother, there's no employment. And when you'll go to vote, you will forget all of this. At that time, you will see caste, you will see Hindu-Muslim. You voted after seeing the face of Modi, so the tea-seller Modi became the Prime Minister of the country. You voted after seeing the face of Lalu ji, then the buffalo herder Lalu became the king of Bihar. Listen to my advice once, vote once after seeing your children's face. Your children will not remain unemployed. Your vote has that power. You're giving almost the same speech in every village. It's new for every village. No.

Have you written it? No, I don't write anything. A written text? Nothing, never. So it's your brain, right? Yes, that's it. And it has evolved like that. You feel it's the same. Because today you're listening to it in the morning and evening. No, I've seen your last 20 speeches. Yes, last 20. But when I started the journey, if you listen to that speech and this one, you'll see a difference of 80%. Got it. It keeps evolving and it's getting fine-tuned, each sentence. According to the reaction you get from the crowd, the incremental improvement, you call it, that's the change. I don't check it in the change. So, you as a performer, do you ever think in your daily life, ok, I should use this word or its pronunciation? Do you have to do it as a performer? No, I just go and sit there. I just stand up and start speaking. Sometimes, I feel like I'm not doing it right. Right? It happens. Like, you're delivering a speech 10 times. Yes. So, sometimes when you're getting up, When your name is being announced, they know that you're going to speak and people have started clapping. But you don't feel like saying anything. Oh, it happens. It happens. You feel tired or you are not in a good mood. When was the last time? In which village did you perform non-committedly? Before New Year eve, my throat was sore. And when the mic was given, the people who spoke before me, I noticed that it's a horrible mic. And the crowd was a bit big. So I thought, I'm done today. I don't have a mic, I can't speak loudly, and the crowd is big, so it's going to be difficult to manage. So I see things like that, and they affect me.

Many people think, you used to work as election strategist what are you doing now? In my opinion, there's no difference between the two. Earlier, I used to do the same thing for the leaders and parties. I used to go and explain to them or help them how to organise your party, how to fight elections on certain issues, how to effectively convey your message to the public, how to respond to your opponent, if they're doing something. I was doing the same thing for the leaders and parties. Now I have enlarged my canvas. And I said that I will not tell the leaders and parties, I will start telling the society. Obviously, when you tell the society, it will look far more chaotic because they are not organized as a unit. But this society will come up with a small subset and it is coming. When I started the journey, I had in mind that in every block, the unit below the district which has a population of 2.5 lakhs, I will find 20 good people from every block during the journey. If 20-30 people come out of every block, it will be 12-15 thousand people. And if all of them make a party, then the power of 15 thousand people will be great. When I am doing this journey, 2 - 2.5 - 3 thousand people are joining from every block. And because of that, the whole padyatra's pace has slowed. I wanted to do this in 1.5 years, but it's been 16 months now, I have been able to do half of Bihar. How many shoes have you lost in the journey?

This is the fourth. Shoes get torn. Yes. When you walk on this road, this is one new learning I must share with you. Okay. I never thought that shoes, I mean, if you walk on a bad road, it will get torn so quickly. And I mean… It is getting torn. It gets torn from behind. Yes. It gets torn by wearing away. There is no need to wear off, it gets torn like this. The road is so bad, because we, I mean, today when you walked, we walk less on normal roads. We are walking in the village. Okay. So, when we are walking in the village, where there are rocky roads, and the roads are broken, the shoes get torn very quickly. How much are the shoes? How much is it? Indian National Rupees. These are Asics shoes. They cost around Rs. 12,000-13,000. The shoes of Asics are very good. Yes. But even these are not lasting for more than 4 months. Whose funding is the Yatra?

Yatra, the whole campaign It's funded by people who have been helped by me in the last 10 years when I was doing it as a profession. Okay. So, in those states... And does that include the Prime Minister then? No, no, no. What? I mean, when I say people, I mean, the people who have seen my work... Okay. In Bengal, in Tamil Nadu, in Andhra... Where they have seen that Prashant Kishor can do something. Okay. In their eyes, whether it's good or bad, that's a different thing. Okay. So, are there any government people who are running the government there? Government? How can the government be involved? Government? No government can give money. Correct. If you are an individual, an industrialist in Andhra Pradesh, you have seen my work, or you have become an MP with my help, or I have helped you become an MP. The people you have helped, the people you have helped, they are helping you. Social capital is coming handy. Yes, using the social capital. I say everyday that the money is coming from there. I have never taken a single rupee from anyone in Bihar. Okay. I have never taken any donation. Is your own money also being spent? Yes, whatever I have earned. How rich are you? Huh? How rich are you? You must be very rich from this work. I am not rich. If it's too personal, please let me know. No, no, not at all. I don't have any money in my account that will tell you how rich I am. Rich people don't keep money in their accounts. #RichPeopleTactics No. Come on, man. No, if you're saying that I have unaccounted money. I don't. No, I'm saying that because you want to bring such a big change in the society, I think we should know about your personal belongings. Of course, you should. And personally, I come from a middle class family and I have no interest in personal wealth or personal assets. Do you make sure that there is no unethical money in this? It is very difficult to say. Because I cannot give a certificate of who's money is this and how he's earning it. However, I can say that, for the entire campaign, I take every rupee in cheque and spend it through the same. Okay. All accounted for. Yes. Accounted for means no one can say that they gave the money in cash. Or we gave them in cash. If you have to give 10 rupees, you have to go to Jan Suraaj and donate it from the bank. What is your selfish motive?

My motive is that I want to see Bihar in the leading states in my lifetime. I have such a big motive and I openly say that I have come with this dream. What will you say 'agraniya (leading)' in English? It should be in the top 10. Top 10? Top 10. It's the last one. It's 28th. And do you want to hold government office? No, no. That's not a priority for me. It's not a priority for you but do you ever want to hold it? When I came to Bihar in 2015, the government of Mahagatbandhan that came into power, I had a say in the entire government. If I had to hold a government post, I would have holded a government position at that time. Who was stopping me? No one was stopping me. Lalu, Nitish and the three of us, we made all the arrangements with Congress, made all the strategies, won the elections, won 190 seats. Who will come to the cabinet, who will get what portfolio, I had a say in everything. I have no hesitation in admitting. But Bihar did not change because of that. I told you in the beginning that until there is an intervention in the society, until people are aware that you hold your elected representative accountable for the deliverable which you seek, till then there will be no improvement. Even if Prashant Kishor wins and we know that the people will vote for us, I will not work with that attitude. I am giving you a figure.

The states of the south that are doing well. In the southern states, no one has been the Chief Minister for more than 10 years. The people there, no matter how much you have delivered, you will be turned replaced. Is this a symptom of development? No, it's a symptom. Because as the aspirations rise, people expect more from the government. They want more. They want more. And it's not just about India. If you look at the data of the world, It's very difficult to have one person or one party in America who has ruled for 30-35 years. This is only possible in the backward countries or states. This is a very fascinating thing, that you have spoken. You see, in Odisha, Madhya Pradesh, Bihar, whoever comes, one reason for this is that politics can be done in two ways.

You can uplift everyone, but if you uplift everyone, on every parameter Then their aspirations will also grow and you will have to work to manage it. The second way to manage everyone's aspiration is to suppress everyone so much that people feel that they are getting only 4 kg of grains, this is too much for us. They are god for us. But is this done intentionally in Indian politics today? Or Indian politicians don't know how to uplift people? No, there are many politicians who have this thought that if you show too much of development then managing aspiration is difficult. And you have worked with these people? Yes, yes. You know that these are their intentions? Yes, yes. These are their... I mean... They have it, said and unsaid in their subconscious mind. And you took money from them and worked with them. No. I didn't take money and work with them. That's not the matter. I'm telling you that... Still, I mean… Let's indulge in that humour. I have helped them. Let's indulge in that humour. No, no. I'm telling you. It's not about humour. It's the truth. This is a sad truth. I say it every day that the people I worked with... I can't claim that they are all good people. I helped Nitish Kumar here in the 2014 and 2015 election. And people abuse me.

Many a times, people say, whatever you say, whatever ill-affect is there, you helped them in winning the 2015 election. That's right. They are absolutely right. So, there are two things. There is a difference between the Nitish Kumar of that time and the Nitish Kumar of today. And secondly, if I helped them at that time, and if he didn't do the work, I will oppose him with the same strength. This is democracy. In democracy, there is no lifelong bonded labour. There shouldn't be. But you will see, what happens in most places, in the name of ideology, in the name of religion, in the name of caste, once you join someone, I voted for Modi ji, so I will continue to vote for Modi ji. I am a voter for Lalu ji, so I will continue to vote for Lalu ji. This is the fight for ideology. Sometimes people ask me what's your ideology. I say there should be an ideology. But, in the intoxication of ideology, I don't want to become a blind devotee of ideology. Correct. That I am a believer of the communist ideology. So whether the communists do good or bad, I will carry their flag. I am a believer of the BJP's ideology. Even if a poor man is being lynched on the road, I have to support him because that's my ideology.

Should I ask a personal probing question or an easy question? Ask whatever you want. I have never told anyone what question to ask. You have come. I have come from there. I have never asked you anything, I have never met you. And this is not only for you, it is for the public as well. The public can stand up and ask any question. #NoRokTok #YahaBenefitKarSakteHain Do you have the guilt of making anyone win? I have been asked this question many times. that is there a guilt to make someone win. For example, if you're a supporter of BJP, you'll say you helped Mamata Banerjee win, you don't have any guilt? If you're a supporter of Mamata Banerjee, you'll say you made Modi win, you don't have any guilt? I'll say it straight, I don't have any guilt. Not even for a second you think, I wish I didn't do this. No, that's a different thing. Come on, tell me something genuine. I'm not the kind of person who regrets about my decisions. I'm the one who learns from the decision and makes sure that if I made a mistake, I don't repeat it. Which is fine. So my question would be... But it's not a guilt. I don't regret, I don't have any guilt. I learn from it. I might have learned from it. Perfect. My question then would be, is there any campaign that you think, I made a mistake there. Is there any such campaign? Or there ain't any. No. Or it is there but you can't say it on camera? No, no, I can say it on camera. There is no problem. The time, the area where I helped, I did it with a clear mind. If I, as a voter, a final check that I use, that if I had to vote in this election, So, who would I vote for? So, in 2017 you would have voted for the Congress and not for AAP in Punjab? You are saying that? Yes. If you were there? Any day. Got it. Any day. It won't happen that I wanted to vote for Akali and I did the campaign for the Congress. I won't do that. It's not that I did it out of greed or out of delusion. The decision that I took, But you must have taken money for that work or you didn't? No, I'm telling you this, I never took professional fee.

The goodwill that was made, I'm taking it back today. Okay. I have never taken professional fees from anyone. I have said this to people many times. Yes, people will have to pay for the campaign. You will have to pay for my expenses. But it's not like we open a shop and you come and say, okay, Prashant Kishore is here, we will pay him 50 crores. I have never made a relationship with anyone like a vendor. You can say that I am more interested in importance than that or more greedy than that. I don't want to be a vendor. So you want more long term gain? I want to make relationships. I want to sit next to the chief minister and talk to him. You want that? I want that. I don't want money in my account. Who is your favourite actor? I don't watch movies.

But you must have seen in 1980. Yes. We were kids then, so we used to watch Amitabh Bachchan Which is Amit ji's favourite film? Have you met him? You must have met him. Do you think you are more famous than Amit Ji? No, man. Amit ji is such a famous man. Do you think you're more powerful than Amit Ji? No. I don't want to compare myself to anyone. You just need power. Isn't this power that you're sitting next to the CM? Sitting next to the CM, you're taking it literally. I want to deal with people equally. I don't want to be their vendor. That's just a status. That's not about power. That's my self-esteem. You must have never seen me taking selfies with the leaders I work with. You don't need it also. I don't do it. I'm not their fanboy. You shouldn't be. I've never been fanboy of anybody. Except for Gandhi? I never got a chance to work with Gandhi. I hero worship him. You do worship him? Yes, you see there are pictures of him everywhere. I read his books. I try to follow his ideas. I do what I can. His family had a lot of complaints against him. Does your family also have complaints? Do you have time for the family? No. They have complaints and we fight. You don't have time?

I don't have time but now my family is used to it. You are married, right? Yes, I am married. Do you have kids? I have a son. My wife is from Assam, she is a doctor. Okay. They are… Do you have romance in your life? Romance? Well, I had a love marriage. That was many years ago. Is she also a workaholic? No, she is not a workaholic. My wife is a smart worker. I'm a hard worker. She's from Assam, you're from Bihar. I'm a hard worker. She's a smart worker. And we laugh also about it. She says, no matter how smart you are, you're a hard worker. I'm a smart worker, so I don't have to work hard. Slowly, as a couple, you get used to and adjust to the plus and minus of your partner. So, somewhere or the other My wife must have felt that this is how it is, and that's how I am. And their contribution is that they are supportive. They are supportive? They are supportive. Then only I am able to do what I am doing. Is your son involved in these activities? No, no, no. He's too young. He's in class 8th. My son has come here once in the last year and a half. People don't come here. Where do you live apart from this? I live here. In which city did you live before? I have a house in Delhi. You have a house in Delhi. Yes. Have you gone to Delhi in the last 16 months? Yes, I have been there once or twice. Once I fell sick and went there. Another time, it was my son's birthday so I went there. How do you celebrate your birthday? I don't celebrate my birthday. When is your birthday? Is Gandhiji against birthdays also?

I don't know about Gandhiji's birthday but I don't celebrate my birthday. We all celebrate Gandhi ji's birthday I don't celebrate it. Why? I have my personal reasons. I can't tell you. That's why I'm not celebrating. No one knows. I don't tell anyone. We'll find out. I'm saying it on camera that my official birthday is That's not my real birthday. So, like every Bihari, your birth year is wrong in your birth certificate? No, the thing is, in Bihar, when you were in 10th class, the certificate written by the teacher, that's your date of birth. Okay. So, the date is written in that way. The date can be changes, but the year is same. Your parents are alive? No, they're not. No, no. I lost both my parents. My mother...

Who were you closer to? It's a very difficult question. I was very close to them, but closer to mom. But I would have spent many more hours arguing with my father. My mother was my blind supporter. Tell me the most beautiful thing about your mother. She was my blind supporter. Whatever I did, whether she understood it or not, then ultimately she would say that if he is doing it, then he is doing it right. When did she pass away? 2017 So she saw your career? Little bit. They saw the victory in 2011-12 in Gujarat. They saw it in 2014. Their happiest moment was when I won Bihar. 2015. What was your father's politics? My father was a congressman. Full time congressman. And a big fanatic congressman. Did your mother have a strong politics? No. My mom was against politics. My father was quite popular in his own way as a doctor. So there were a lot of times when there was a temptation that he would get into politics. But my mother was against it. Can you describe that village for me? The village you were growing up in? I didn't grow up in any one village. Because my father's job was transferable Where your father used to get transferred. So we were nomads in the past as well. We were born nomads. We were born nomads. I mean, I haven't had a home where I've lived for a year or two. My neighbours, the normal life of people, they are my friends, they are my neighbours. I don't have anyone. You don't have anyone? Like people say, I have a school friend. Don't you find people interesting? No, no. I have.All are left behind. No, that's there. If you want to stay in touch, it's the digital age. No, it's the digital age. But different people from different backgrounds, different perspectives. When I was in school, the school was in Bihar. Now their life is different. My life is different. I left. Did you meet anyone in the United Nations? No, I am not in touch with anyone. Now, let's say I was in the United Nations. Now, it was in the Francophone world, in Africa, in the US. And what I'm doing in Bihar today, no one will match the time, interest, or you can meet or talk to me. You must have seen Swades? No, I haven't seen it.

I haven't watched movies since the last 20 years. You haven't seen Swades? I haven't seen any movie for the last 20 years. I don't watch movies. Have you seen Narendra Modi's biopic? No, I haven't. Have you seen The Accidental Prime Minister? No, I haven't. I don't watch any movies. You don't watch political shows? I haven't. You haven't seen House of Cards? No, I haven't. Do you play cards? No, I'm a chess player. Okay, so you play? I like to play my move and then you too respond. Wow, that's viral. We don't hide. I don't believe in that. I don't do the backtalk. I do everything on the face You don't do the cheating? I don't think it's necessary. Have you ever done anything unethical?

If I say I've never done anything unethical, it's wrong. In the profession you were in for the last 10 years? Yes, you do the unethical things. The biggest unethical thing is that there is a limit to expenditure in elections and you know that more is being spent than the limit. That's true. It's more than 50 times more. But the election commissioners don't see it. They also see it. Everyone knows that it happens. But this is a convenient situation. But how dirty does Indian politics go? It can get as dirty as you can think. People are ready to do anything at the individual level to win. Do you mean to say that heinous criminal activities also happen? I haven't come across anything like this but I wouldn't say that it doesn't happen. You have been in this industry so you must have observed something. It's not an industry but in this domain, the reward of winning is so big that people are willing to go to any extent.

People compare Mamata Banerjee and Narendra Modi in terms of their dictatorial tendencies and how much they sometimes devalue institutions. I am telling you that the democratic institutions in India, they need to be strengthened. That's fine, but you did work with them No, no, it's a function of why an individual is able to take it. It's not that Narendra Modi is doing it and Indira Gandhi didn't. Any powerful leader, they are able to do it and that's why mature democracies, better democracies, I won't say better, but much more mature, evolved democracies than India's, have probably learnt that when a leader is very powerful, and popular, he or she would have tendency to kind of overpower or manipulate. That's why as a society we should invest in building the institutions and the framework and strengthening them rather than talking about if Indira Gandhi had more dictatorial approach or in Narendra Modi. I said Mamata Banerjee in Modi, not Indira Gandhi in Modi. No, that is not comparable, it is a matter of state and centre. It is not comparable. But will you see any value in the criticism of BJP voters about Mamata Banerjee being more important than institutions? Do you see any proof in that? Or you can't say anything? No, I'm talking about everyone. You might be good friends with her. No, I'm good friends with everyone. I'm no friend of... I asked Mamata and Modi and you constantly said Indira and Modi. I did it because... So my feeling is that... No, I did it because you cannot compare apple with oranges. Indira ji has run the country, Modi is running the country. Congress and BJP can be compared. Now Mamata ji's comparison should be with the Chief Minister. I will ask Yogi and Mamata in the next interview, but that's for another time. Let's stop this now. Give me 5 minutes. Give me 5 minutes. How do you win elections in India? If there's one thing, key to winning elections in India, how do you do it?

Listening to people. This is the most underrated virtue. The one who sits on a chair, he can't hear. When you go there, Nitish Kumar thinks that the alcohol ban is in place in Bihar. What are you saying? He doesn't know that it's available so openly. I am saying, I can bet my neck, he really believes that the alcohol ban is in place in Bihar. Mr. Prashant ji, I have... Mr. Narendra Modi is feeling that the whole country has changed and no poor person is left. What are you saying? He knows it. I am telling you, people don't understand. This is a very big thing. Why does the person sitting on the chair get anti-incumbency? Slowly, slowly, slowly, that thing doesn't reach the leaders who sit on the top. They keep getting isolated. Yes, and the more successful leader is, the more he tries to make him hear the bottom line. The cliché we say that in the older days, the king would come out in disguise at night. That one line sums up. Why was the king said to come out in disguise? As long as he is in the disguise of a king, he will not know the truth. As long as people know that you are a king, they won't tell you the truth. In the last one and a half years, when you are listening to the ground, have you grown in respect for the politicians or for their work? No, I always respect the politicians. I am not one of those people who thinks that every politician is corrupt, no one wants to do anything. The thief is also working very hard. It's not like that. People who have seen Hindi movies have made an image of the politicians. That's true. No, the politician has won and he's sitting in his room scheming how to loot. He's scheming but he's scheming how to earn money and keep the people happy. That's a complex scheming, not so simplistic. Not so simplistic that you're a politician and you start looting. I haven't found a politician who is 100% pure, all about theft. You haven't found anyone? Which politician surprised you the most? He's a very genuine man. No, no, many people surprised me. Still, give me a name. No, no, many people. Come on, put something viral. No, no, I won't. Come on, man. No, no, many people are sitting here. One more question can be asked. No, I'll talk about it later. What are you talking about? I'll talk about it later. I'll talk about it later. Absolutely.

Mr. Prashant Kishore is here. Please welcome him with a big round of applause. Mr. Prashant Kishore From this sacred land of Begusarai, from the sacred land of Salona village, Mr. Prashant Kishore has come to meet you all. He has come to meet you all. There are two lines. "The traveller will go till the point where the path will leads... Oh! One more time. "The traveller will go till the point where the path will leads... How can you ask the river how far will the water go? Pull the bowstring. It's a bowstring. Yes. Pull the bowstring. Aim for your target. We'll see where the arrow lands. Wow! I said the last line. Silence. He's here. Is PK here? Yes. Okay. We could've heard one poem. It was going so well. I'll have to take an interview. I mean, we've been waiting for 4 hours for you. 2 hours here, 2 hours there. That's what we're good at. Waiting. Yes. Before you came, there was a talent show going on here. What was going on? You have amazing poets among Padyatris. Amazing poets. One singer too, he wrote very well. He wrote on your speech. Oh, okay. Okay, who's the orator you look up to?

Is there any orator? Only in oratory. Only in oratory. That, yes, this part is very good. No, this... Come on, Prashant. Be a little candid. I don't like to say that I like their oratory. Then it will be a stamp of approval. No, it's not a stamp of approval. They are big people. You do care about what you are saying in this interview, right? That I shouldn't praise them. I can see that. It will be childish to say no. No, no. When I do interviews, I am very candid. Whenever you see my interviews... I can see the truth in your eyes. No, the truth is, I may not be able to say what you want to hear. No, no, I can see it. But I am never guarded in an interview. No, you never lie. But you are always careful, can I say. You are careful. No, the only difference is that the choice of words on camera and off camera can be that much different. The rest, I mean, what I want to say, there is no difference It's in the choice of words. Yes, but if it's off camera, then maybe the words are a little loose. You curse? Have you ever done it off camera? I won't ask which one. Yes, sometimes. It comes off the gut. When did you last get angry? You got angry. It comes off everyday.

I was watching you, you were wearing so many garlands. you were not able to breathe. What happens is, when people throw garlands, who are a bit short in height they jump and throw it. It hurts a lot. Women have their bangles, they hurt, I get cut. Many times, there are problems. But now it's okay, when you put your head in the hole. Because you are seeing, unlike other padyatras, I don't make a ring. I mean, there is nothing around me. Whoever wants to come, push me, put a garland, take a picture People try to boast by saying that I am the chief and I am in danger. I will sleep in the tent, even a dog can get in. What new things have you learnt about Bihar through this journey?

I learn new things every day. Are there any notions that have broken? I mean, Bihar looks poor in numbers, but when you feel it in person, it's like the difference between the two worlds. Is it more in person? It looks very scary. When you see it visually, interact with it, sometimes...you feel anxious. It's so scary. You feel anxious. How will it improve? How far have we fallen? Quite common, if you sit in any assembly, you will find 5-10 old women, old men who say that we have nothing, we get a pension of Rs. 400, that is not even coming, the children have thrown me out, I have no home. I get scared, I think for hours, how do they manage in Rs. 400? And the state authorities don't care? See, the state authority is giving 400 rupees so they'll say we are giving it to them. If you go and ask Nitish Kumar, he will tell you that he has done a huge favour. And it is not that the state doesn't have enough resources to make this 400 rupees 1000. It is not that if you give 600 rupees, Bihar will go bankrupt. But there is insensitivity and a sense that what we are giving is a lot. Is it such a black age for Bihar? It is, it is. See, India will be a poor country on a per capita basis, even if the government claims anything. The country's per capita income is Rs 1,35,000. In most districts of Bihar, the per capita income is Rs 25,000-30,000. So we are like one-fifth of the Indian average. So you understand the state of poverty here. And I'm talking about per capita income. Don't even talk about the lower income. Around 70-80% of the people here don't earn even 100 rupees a day. They don't earn 100 rupees. It's that close. You must be roaming around the village. Absolutely. Around 50-60% of the youth have migrated. They all went to other states, to work as labourers. Someone from your volunteer base asked me if we are fighting 2024 elections.

Lok Sabha? No, I tell you every day that we are not fighting Lok Sabha. How will Jan Suraaj contest the elections? I will tell him. For Lok Sabha, which I am saying everywhere, I will only form a party when I go around Bihar. And it won't be formed till May. How will it be formed? It won't be possible. But, this doesn't mean that no candidate from Jan Suraaj can't contest the elections. When we walked in five districts, The MLC has won too. A man came and said, you are talking about education, there is an MLC election on education, let's fight it. I made everyone sit down and said, He was elected and fought for it and won. So, it's possible that in Lok Sabha, I see someone in a district who should be in the parliament. So you can come in support of him? Yes, but he will fight without a party. Jan Suraaj will not fight as a party. But at such a big level, whenever you fight for elections, how do you make sure that, There is only one danger, right?

Dilution of vision, ethics, passion, whatever you call it. You understand what I am saying? Absolutely. When the topic is so widespread. I tell you, pure gold cannot be used to make jewellery. You can make biscuits out of pure gold. But when you make jewellery out of it, you have to mix 2 carats of gold. The society considers 22 carats of gold to be pure gold. They believe till 18 that it's a gold jewel. But if the mix is too much, then it's not gold, it's rolled gold. There will be some compromise. As long as the gutter is in the Ganges, there is no problem. Ganga shouldn't be mixing in the gutter.

In your organization or in your party in the future, are there like protocols in your head to put in place? Or you haven't reached there yet? No, we haven't reached there yet. But the biggest thing you do is to publicly commit. That is the biggest... That's your expectation. I think that... Because there's a tendency that you want to get it immediately. But if you've publicly committed, then you think, how will I do it? I've said it so many times. But how true is the intent? No, it's not about the truth of intent. It's the pressure of how will I show my face to 100,000 people. But I'm saying... If you once... But I'm saying, Mr. Prashant… You can ask Nitish Kumar, even if he has to go change sides three times. After every turn, you have to kill your conscience once. Why is Nitish Kumar called the Paltu Ram? In this political setup, it's not like no politician has changed sides. But so frequently... That's crazy. Nitish Kumar is the one who takes 180 degree turns. So, it's not everyone's cup of tea. Right. It's not everyone's cup of tea. It's Nitish Kumar's cup of tea. What do you feel about him personally? No, personally I had a great equation with him when we were together. I said it on camera that we are like father-son. The situation is like we are sitting during the winters. And if I am not wearing socks, he will not let me get up till I wear the socks. He takes care of me like that. Have you worn socks? No, I am wearing them now. No, I am telling you. But that's beautiful. I have never heard of two politicians, even within the same party, have such intimacy. People don't say it publicly. No, no, I mean, I used to live with him. We used to live together. In the same house? Yes. You lived in the same house? Yes, same house. I lived with Amrinder too But he gave you the cabinet rank, right? Who? The captain. He never did. He announced it, but I didn't take it. Okay. One question that is not mine, but I think it should be asked. Okay.

Someone asked me, in 2014, I mean, you were with Modi Ji in two elections. Gujarat and India. So... 12 and 14. Yes, 12 and 14. So the question was, that this thing is in your CV, so will the Muslim voters have any problem coming to your side because of this? Now look, the fact is that it is in the CV, it is upfront. It is not something hidden. But if it is in the CV, then it is also in the CV that after 2014, wherever BJP lost, Prashant Kishore had a role in that too So, if Muslims remember 2014, Bengal also remembers. How unhealthy is India...not the overall democracy but the way the naysayers say that the Indian government has a lot of institutions, takeover and all, is it as extreme as that? Obviously, it's not as positive as a BJP supporter would say. But is the truth somewhere in the middle or is it going towards a darker era? I don't know. The problem is not that they are winning. Or they are winning big. Or that the government has been in power for 10 years. Or how many states have the government. There were bigger governments than this, this country has seen. The problem is that BJP wants more than your vote. They want to leave an ideological imprint on you. They want a psychological dominance on you. Whether you want my vote or not, that's a story. Now after that, you gave me the vote, okay, you should also worship them. Wear clothes like this, eat this food, don't sit with them, befriend them. They are taking over your life. So, when any dispensation tries to go beyond what is legitimately their job, so, if you are infringing on the job of the government or the job of the political party, then that is a thing which one should be careful. That's very well said. It's a quotable quote. Thank you. I don't meet a lot of politicians who give me quotable quotes. Hahahaha! You're not... You're not meeting a politician. Hahaha! But you do work in the domain and not the industry of politics. So yes, you're quoting it back. Why are you getting so serious all of a sudden?

Are you not allowed to laugh? No, I laugh a lot. I laugh a lot. Laugh loudly. Hahaha! Hahaha! Hahaha! Hahaha! You are a funny man! Of course! Do you dance? No! Aamir Khan or Salman Khan? Aamir Khan! Well said! But Shahrukh Khan or Aamir Khan? Aamir Khan! Oh! Which film of Aamir Khan? Or what work? I liked Taare Zameen Par. Beautiful film. That movie made me cry. You haven't seen any of my interviews. Never. Never? Okay. My name is Samdish. Hahaha! That's why. I've heard a lot of good things about you but I haven't seen any of your interviews. Okay. See this one. I won't see mine. Watch the one with Omar Abdullah You send me one, I'll see. Sure, sure. Will you give me your number? Hahah! Number?

It's publicly distributed. No, no, the real number. My real number is publicly distributed. Then I don't want such a common commodity. If it was rare, I would take it. I'm telling you. We have an ambition too. My number, I haven't changed it since 2011. Oh. It's a commodity of the whole of India. What messages will be there in it? What messages will be there in it? And also understand how many people track it. Yes, every government is tracking it. The one I am working for is also tracking. The one I am working against, at least 20-25 people are tracking me. That's why I don't change it. What's the point of changing it? Someone else will track it again. So I left it as it is.

Do you ever Instagram? You never check? Don't say it so disgustedly. What kind of question is this? I don't have any. I'll tell you one thing, I've never posted anything on Facebook in my life. People think I'm a social media wizard. But you understand the importance of social media? Yes, I understand data, I understand communication. But if you tell me to make a post and post it on Facebook, I won't be able to do it. What was the last data point or figure that astonished you? Because you're a man of numbers. So what was the last thing that you thought, what's going on? I don't get surprised that easily. The population distribution of the country, two-third rural population lives in less than 20% of the villages. One second. Say it again. Like in India, there are 7 lakh villages. But 90% of the population lives in 1 lakh villages. And that was like, wow! That's a densely populated village. No, not densely. You have to see how sparsely populated the other 6 lakh villages are. Sparsely populated? Yes, sparsely populated. That was like, when I looked at it a few years back, it was like, wow, this is a real gold mine for me. Man! I mean, this thought came to my mind, let's see the spread. Is there any way that we can reach the vast majority without going to 7 lakh villages? So that we can see the spread. Is this what got you to Bihar? No, it holds true for whole India, including Bihar. If you touch 12,000 villages in Bihar, you are done with almost 80% plus population. Okay. Instead of 40,000 villages. This is a very dangerous data point. It's not dangerous, it can be used. Yeah. You do marketing too. Suppose you are selling surf... Yes, yes, it's very useful. So, if you know that I am targeting 12,000 villages and reaching 80% population. In such an efficient way. In an efficient way. Don't you ever get bored of politics? No. You must feel fatigued sometimes.

No, I'm fine with it. You're obsessed with it? Obsessed with it. You have a little insanity. Yes, you can say that. Stability scares me. I'm one of those who loves pressure. Stress. So, the more stress I have, the better I feel. And my BP will keep getting normal. I am telling you, when I am very tense at home, I am in a lot of trouble, and I feel I am under a lot of pressure, I tell my wife to check my BP. So, I am sure that I will get 80-120. The more, the merrier. Okay. Have you ever thought of taking therapy? No. Never thought? Never. Never. Oh, you think I'm a bit...

Hey! ...shaky. Everyone knows that, but I don't say that. You're saying it. Oh, no. I never thought of that. No, therapy is not only for shaky people. I take therapy, I'm not shaky. No, no, that's fine. No, it's not needed right now. We'll see if it's needed. It's fine till now. Do you sleep well? Is it a peaceful sleep? Yes, yes. I sleep well. I don't sleep enough, but I sleep well. How much do you sleep? Are you like the Prime Minister? No, no, I won't say all that. Should we create that folklore for you? No. That PK also sleep for 4 hours. You must have created all this. No, no. All this is your suggestion. No, no, no. Come on. It's not like that. PK ji. They are enough to make their own folklore. But that magnanimous figure has a small contribution. No, brother. Two drops in the sea are of you as well, come on. It's possible. Come on, man. Who asks two drops in the sea? We are asking. We are sitting with you. Is legacy very important for you?

How people remember you? Yes, because I have not inherited a legacy, so I would like to leave a legacy. It does seem very important to you, how people remember you and what you leave behind. Yes, yes, yes. It's very important. Bihar's context is such a deprived society that people go from here to work as labourers. A guy going from here to advise the CM is a matter of pride for the people here. How important is it to be arrogant for a political leader? Not you. As a virtue. As a virtue, you need a little narcissism. You have to be, like when you are an actor, you have to be in love with your own face and appearance. You should feel that the world is in love with me. My looks. My physique. Otherwise, I keep saying that extras are taller, more handsome, have a better body. But this attitude... That I am the sun. I am the sun. The world is out here to see me. A politician needs this. Just a little. Just like politicians need this. This is a requirement of a job. A little narcissism is a must. So can I call you a politician or not? No, I am not a politician. What is this? This is very convenient. Who is the leader of Jan Suraaj?

The leader of Jan Suraaj is the one who makes this. Whose name does this announcement that goes to the villages take? Prashant Kishor, the leader of Jan Suraaj, who has been walking for 16 months. He doesn't say that he is the leader of Jan Suraaj. Is he the leader or not? Come on. No, he is not the leader. I say the first line that I am Prashant Kishor and I am not the leader. How do you differentiate between the facilitator and the leader? What is this? This is very convenient. No, this is not convenient. Okay. Is this an important differentiation for you? It's a very important thing. I don't own it. Jan Suraaj is not owned by me. Like I tell you, Gandhi was the leader for Congress. But he never claimed to own Congress. Whether I will stay, my son will stay or whoever I want will stay. Okay. That's a big differentiation which we say is okay. Do you feel you relate to Gandhi because of Africa, India? No, no. Do you have that kind of complex inside you?

No, Gandhi. I was in 11th and 12th in a science college in Patna. My father was the Chief Medical Officer at a place called Buxar. He was on the rail line. We used to catch a train from there to Patna. We used to go home and come back on the weekend. At that time, there were some trains that didn't have tickets. There was a 400 km restriction. You couldn't get a ticket for less than 400 km. You were not supposed to get on that train. So we had to come without a ticket. We used to get on the train and talk to the TT. I saw a Gandhi's mantra written on the train station. It was written to stop the ticketless journey. It was a mantra to tell the passengers that the train will not run until they buy the ticket. I used to read every 10–15 days while coming and going. I thought, what a stupid thing to do. A person like me will never buy a ticket. So the train will not run. But almost 6, 8, 9, 10 years later, I happened to be in Germany. So, I saw people coming there and no one was checking their tickets. People were swiping their cards. At that time, I felt that this man had said that 100 years ago. And today, I am here. He was so far-sighted. What West is doing now, he was recommending this 100 years ago. Now this is my own life experience, whether it's small or big, relevant or not. This is one thing that got me to start reading about Gandhi.

You're 45 now. Is there anything about my generation, about a 25 year old person, about this generation that you don't like? Too much time on the screen. It's not a question of passion. I think we probably do not know enough about what psychological and physiological impact it is going to create. We are all shooting in the dark. For example, the brain's evolution with one hour no access to internet or mobile versus two hour versus eight hours. What does it do to your brain. Nobody knows. And hence it's like feeding your child a food which you don't know is good or bad. If you knew that after 30 years, this will have a negative impact. So I don't know the use of technology, especially the use of screen, what it is doing psychologically and physiologically to the kids, especially those who are still in their formative age or growing up age. No matter how smart you are, no matter how disciplined you are, no matter how reckless you are, we are all sailing in the same boat. Do you talk to your son about this? No use. No use. He doesn't believe you. No one will believe me. I'm saying myself, my screen time is 5 hours, 6 hours. So what do I tell others? But what is safer, Signal or Telegram?

No, this is nonsense. Nothing is safe. It's all illusionary that this is safe. Some people say, WhatsApp is compromised and FaceTime is good. When I called, they said FaceTime is compromised. How did you check? The lab at Amnesty checked it. When Pegasus came for the first time, they called and tested it. They said, your phone is compromised. So I told him that I have a 4th or 5th handset and he checked all the handsets and said that they are infected. I asked him what's the next solution and he said there's no solution. I told him to leave it, was depressed for a day then I left it. What can I do? Did you think about it one day? Yes, I thought about it one day. It's a big problem. But allegedly the people who must have put it, you worked with their bosses. Allegedly? We don't know. It might be Rahul Gandhi doing it. Who knows? I know that it was in my phone. 15 Pro? No, not 15 Pro. I use the old one. Okay, fine. What color? What color? The color is black. Okay, fine. What's in the screen saver? There's nothing in the screen saver. Show me something. There is nothing in the screensaver. Oh, alright! It's normal only. Oh! Nothing is there. I thought it will be Gandhi ji. Okay. I don't do all this. Okay. Okay. I don't do all this. Haha! I don't have fascination for these things. Alright. For me, I'm connected to the world through my phone. Nothing else. I don't have iPad, I don't have laptop, I don't watch TV, I don't read newspaper. I don't take notes. You don't take notes? Never. What do you think? Are you a genius? No, average. You're lying.

No, I'm an average person. My IQ is very low. It will be low if I get a test. Sometimes I get curious and think of getting an IQ test. But if I get a test, then... Come on, this is humility. 80-110 will come. What is your biggest strength? I am a quick learner. I am very adaptable. I am comfortable sitting in a 5 star hotel. And I am comfortable sitting in a village. My ability to bring my understanding from different fields. Like what I see in society, what I read in economics, what I read in Bloomberg. The ability to merge it. To collate it and do some analysis. That's it. I'm a very slow reader. Okay, go on... When I read a book, people say I've read 4 books. It takes me 2 days to read 4 pages. There are hardly any books that I can finish to the end. Do you smoke? No, never.

Have you ever smoked? Never. You never smoked? Never. Liquor? Very rare. Okay. I'm not a social drinker, I'm not a drinker on my own. Okay, but if you win an election... I'm sure the captain must have given you champagne. I have never had at the captain's house. Sometimes I have a sip of wine, and that's it. Okay Otherwise, I don't drink. You went to the Tanzania election? I didn't drink there either. No, but tell us something about that. I didn't do anything. But you were involved. You did fly there. I went there just because I was fascinated with Nyerere. I wanted to see the politics of the country and the party of Nehru's era. But you won the election. I didn't win because I got involved in Bihar and then my colleagues were there. I went there for a few days only. Just like some institutions. I'm talking about I-PAC. I-PAC did help. Yes, but to some limited extent. We cannot take credit for anything there. Who's your favourite Prime Minister of all time? In India? Yeah. Narsimha Rao.

Well said. And one of his contributions… No, whatever India today is seeing in the present era, this economic liberalisation, a great deal of credit has been given to Manmohan Singh ji and rightly so. But I think the real architect of what has become irreversible and non-partisan, whether it is BJP, whether it is Congress, whether it is 'mili-juli sarkar', whether it is Chidambaram or Nirmala Sitharaman, in every situation, one thing that has become irreversible in the country is economic liberalisation. The pace, texture and contours of the work can be different. And that is a contribution which I think we must give to Narsimha Rao. And I think Narsimha Rao is one Prime Minister who has been underappreciated compared to what he delivered. This is true. People don't recall when Narsimha Rao became Prime Minister, he became head of a minority government. At that time, there was so much uproar regarding Ram Mandir, so much uproar regarding Mandal, economically we were almost on the verge of bankruptcy and from there to reverse it. I think as a nation we have not paid, he might have had his own share of mistakes and faults but as a nation I think as a Prime Minister, especially his first three years were critical and very good to my mind. If you have to find a flaw in JS, what would it be?

JS? Jan Suraaj Jan Suraaj. Come on, man. People are calling it JS. Young people are calling it JS. There are a lot of flaws. But still, you admit it yourself and through this you're telling your volunteers. You can tell them anyways. No, I mean, we are yet to scale up. Sometimes I feel that if I were behind it and someone else was in my place, it would have had a huge surround sound. So you're missing PK- the strategist. Yes, you could say that. So if you could tell us a few points on how you fasten up. There are many things. Please tell us a few. Let me, please give me a peak into your mind. If I was managing this So along the route, I mean, the whole thing would have curiosity. Everyone would have known about the routes of the yatra. A storm would have broken out. Yes, I had that capability. I could make a storm.

So you would have become impatient with your team? Very much. I am always impatient. Everything should have been done like yesterday. The boys who have worked with me, I salute them. I am a horrible person to work with. Why were you angry today? Why was I angry today? When I came in the morning, it got delayed by 2 hours, everything. So I got you angry basically. No, not you. He said, you are sitting here, you have to go to another camp. He didn't tell me, he said, I'm not interested in that, we'll do it here. Because of that, everything got delayed for an hour and a half. He said, I'm not interested in the cultural thing? No, no.

I enjoyed seeing such cultural things. I said, it would be a good thing because that's one thing, why I value it so much. Because it is not dependent on Prashant Kishor. The ones who came here, they were mobilized in the name of Prashant Kishor. They are coming, the talk is going on, let's go and listen to them. We'll show you the way, we'll take you out of poverty. Those kids who come, it's a pure power of what we are doing. I am seeing myself, I grew up in Delhi and around me, there is such a large-scale cultural activity and so much encouragement is being given to kids, which is very like... We do this in every village. And this is something which I have learned from the Padyatri. It was not my idea. They have started doing and it really impressed me and we do it at a very big scale.

It looks so easy, right? That social media has gone viral. The truth is that it will just reach 13 crore people that 'Prashant Kishor' exists. Forget about the merit, influence, effectiveness. There is some guy named Prashant Kishor who is doing a Padyatra If you will ask only two things in the village, right? Where I have come from, where you are seeing so much crowd, even half the people there won't know this. Agreed. They won't know it. Correct, correct. We are one sixth of humanity as a country. That's crazy. When you think of it that way, it's crazy. Imagine... Africa is 1.1 billion. 54 countries. Yeah, dude. The population of France, the state of that population—new guys came here and won overnight. That's correct. But have you got somebody who has won the whole Europe? And that will be also one third of India. Crazy man. So the sheer number are so staggering, it creates, it itself creates a big hurdle for a newcomer to come and make an attempt and do good. Does the average Bihari understand what they are entitled to just on the basis of them being a citizen of this country?

They understand, they probably do not have the full comprehension of it. But they do understand that we need better things, we deserve better things. What constitutes better, they might not have the full comprehension of it. But that they have a right to it and not that... No, no, everyone knows the right. Everyone knows that this is their right? We have the right to want a good life, we want more. What do you want? What do you mean by more? That awareness is not there. Awareness means that there is no comprehension of it. You have not seen it. If you haven't been on a flight, you wouldn't know how it feels. On that note, Prashant, thank you so much. You've been generous with your time. Thank you so much. It's been a wonderful experience. Thank you. He go viral a lot. A lot of people have seen it. You're going to say that? People have been telling me that I should give an interview. Take out your hand and do something like this. Do something. Do something. Do something. I've been doing it since morning. Pick up this chair once. No. Pick it up. Pick it up! Can you slap me or something? No, no. Do something like this. Alright, thank you!`;
