/** Demo transcript for the Conversation → Flowstate playground (admin-only). */

export const RANA_DAGGUBATI_VIDEO_URL =
  "https://www.youtube.com/watch?v=lSRSF7l7-rg";

/**
 * Chapters exactly as the creator wrote them in the video description — YouTube
 * derives its chapter markers from those timestamps, so this list is the one the
 * player shows. Titles are used verbatim; `end` is the next chapter's start.
 */
export const RANA_DAGGUBATI_CHAPTERS: {
  start: string;
  end: string;
  title: string;
}[] = [
  { start: "0:00", end: "6:38", title: "Intro" },
  { start: "6:38", end: "13:03", title: "Why acting is a lifestyle, not a job" },
  { start: "13:03", end: "19:41", title: "Trauma, AI and what machines can't make" },
  { start: "19:41", end: "26:29", title: "Rebuilding after Baahubali and the health crisis" },
  { start: "26:29", end: "32:48", title: "When too much money becomes a problem" },
  { start: "32:48", end: "38:59", title: "Drawing his own lines around AI" },
  { start: "38:59", end: "46:08", title: "Producing his first Hindi film" },
];

/*
 * Auto-generated (ASR) captions, timestamps stripped. Two speakers — Anupama
 * Chopra interviewing Rana Daggubati — but ASR carries no speaker labels, so
 * attribution on any extracted artifact is read from the turn structure and is
 * only asserted where that structure is unambiguous.
 *
 * Disfluencies, filler and mangled proper nouns ("Bahubali", "Mika", "Raja
 * Moly") are left exactly as the machine produced them. Cleaning them up would
 * make every quote unverifiable against the source.
 */
export const RANA_DAGGUBATI_INTERVIEW_TRANSCRIPT = `production does not mean a fancy vacation and vanity that's around you. I was watching an interview that Mika did, right? And of course, she's a mental health advocate, right? So, she's talking about actually slowing down. She's talking about um you know, sort of balancing the hustle with holistic care. And as I was watching, I'm like, I wonder if Rana listens to any of this. Has she rubbed off on you in any way? I think it's been the other way around more. Oh no. Now she's got a bunch of things to do. Like now she has like projects in Bombay, Goa, China. She travels more than I do. She's on calls longer than I and I love it. Say if my health didn't take the turn it after Bahubali, I would have never been part of Amaritra or any of these stories. This year we're working on a lot of young filmm working with a lot of young filmmakers. So the idea is in the next 18 to 20 months can we bring out five to seven films all made by new filmmakers young first- timers.

Rana welcome to the Hollywood Reporter India. Thank you Hollywood Reporter Anu. What's up? Listen, I always enjoy chatting with you because likewise, likewise. I feel like at any given time, Nana, there's like at least three world domination plans. World domination plans. Well, always. Well, I think we're in that space of life and unless the idea is not world dominating, we shouldn't do it. Correct. So, I think that's the place where the world has thrown us into. Correct. Correct. And and you've of course said that the direction for you comes from your legendary grandfather Mr. De Raman Idol who you said came from a village decided he wanted to make movies and then made more than 100. Yes. Which is just scale on another level and you understood from that that if you want to do something just do it.

So what is it that you want to do right now? right now I think uh the focus not just right now the last five six months in in fact have been it's very clear that there is a new generation and a new voice of people uh whether you see watch the news whether you're on social media whether uh the kind of films that are also working in the cinemas uh the kind of audiences that are coming younger audiences that are coming for certain films really gives you a definition that listen, it's a new generation. Uh I remember when I was young, when I was 16, 17 years old, feeling like the cinema that was happening wasn't cool enough. When I was growing up, I thought like this like uh when we did films without songs in them was like a big experimental moment. Correct. Right. These were all things that we were trying to break and and I feel that's happened now with this new generation. I'm 40 42 years old this year and the fact that the 30 is the millennial in some ways and everybody younger is consuming something different is exposed to something different their way of life is different.

Uh so I think uh the focus has been how do we find this newer voice of young filmmakers. I think maybe a decade ago we did a a very organized exercise with ourselves where whether as an actor I kept doing films like Gazi attack or Nin Raj which were quite different from what was happening. We were releasing films like Kerov Ker Palum, Pel Chupulu, all of these new films with new filmmakers, new actors and I remember at that point uh in the office I was I was just about 30 years old and we said now it's going to be an under 30 office and all of them at that point were kids who were younger than the age of 30. I was almost the oldest guy in that camp at that point and which led to a today all a bunch of them are big seasoned actors, popular directors and all this happened when we decided to make just new things right and I think somewhere down the line we lost that energy because also costs have dramatically gone up.

Yeah. uh we were very comfortable making films in 3 to 5 crore rupees and which were grand and they were beautiful looking they had great concepts great actors it's getting harder and harder to do that uh experimenting has also gotten a little more expensive uh so I think somewhere we've gone back to that cautious route of saying listen if you have to make it we have to make it uh somewhere the costs today are somewhere like a complaint that we have in our heads oh this can't get done at this cost this can't get done and there's no real reason uh because in the same time an industry like Kerala is making it at the cost that nobody else in the country so these are possible it's just that I think it's some little effort to get off the high horse and say listen production does not mean a fancy vacation uh and vanity that's around you it's uh it's just a camera it's whatever in front of the camera is all that matters you go back to nuts and bolts yes and that's I think That's the energy that we're trying to carry on. Uh just not with the newer films that we're producing, but films that I am included in as an actor. I just wanted to get that indie spirit back fully uh within the way we make movies.

Nice. Nice. N you had once said that acting is a lifestyle. It's not a job. Of course, it is. Yes. What did you mean? See, you don't switch off from it, right? We don't there's very rare that you switch off from just from anything that you do in the media business because somewhere what you see and what you what you hear is your business. You're either inspired by them or inspired by what you hear or you're worried by what you hear. There's something that's going on from the time you are awake in the morning. You're you're performing to something. Uh maybe not in character but out of character you're performing to something. So which is why I said it's hard to say listen I'm going to shut this off at 6:00 uh where in uh in in any other IT office you could leave and you are logged out we can't log out of anything right we can't log out did you ever log out of your workplace doesn't matter you're a journalist you're an actor you're a producer writer this is it you chose this lifestyle and often I try to tell people like listen this is what the arts means when you've chosen it it's It's not like it's easier than business. It's maybe crazier. It's just that you get to do what you actually wish to in this world. Uh so a lot of times we mistake it for I'll be free. I But that's not how it is. It's a full-time job. It's 24/7 completely. So that's what I meant and I stick by it completely. There's no change.

But R I was watching an interview that Mika did, right? And of course she's a mental health advocate, right? So, she's talking about actually slowing down. She's talking about um you know, sort of balancing the hustle with holistic care. And as I was watching, I'm like, I wonder if Rana listens to any of this because my impression of you is like 30 things, the multitasker of the universe, right? Um has she rubbed off on you in any way? I think it's been the other way around more. Oh, no. Now she's got a bunch of things to do. Like now she has like That's right. She's an art entrepreneur and a mental health. Okay. So you've ruined her. Well, now she has projects in Bombay, Goa, China. She travels more than I do. She's on calls longer than I and I love it. It's great.

So all of that holistic, you know, balance, life, work life balance. I think that's what the movies are. No, in my head, we are already balanced. Correct. See what are we finally doing in our end of the day. Okay, there will be a lot of madness about how to get things done, financial pressures, all that will be there but you are spending majority of your day sitting with an idea that you are excited with or a bunch of people are excited with. Now I don't see any other job or anything else that one can do in life that can keep you so engaged. Yeah. And it's not like someone's put a gun to my head saying listen out of many ideas that have come.

And actually I I actually want to quote a friend of mine Ravi who met me in my Chennai office. He studied with me in school had nothing to do with the movies. He was coming back to India and uh he was in Chennai. We just were there and he came to the office. I was in a narration and in the end of it he said something to me. He said Rana what a wonderful life you have. I said why? He said, "You're just sitting in the morning and someone is coming and telling you a story." And for us, I was like, "Wow, that's truly true." Like, you're waking up at 8:00 in the morning and someone's just coming to tell you a story for a few hours. Now, for somebody else's perspective, that's a great job to have. So, I like these are things that we don't consider being blessed about, but this is slowing down. Yeah. Tell me which person is going to sit for three, four hours and say, "Now tell me a story. I'm not going to say a word. I'm just going to listen and we may laugh together cry together in the same thing and I think that's the process of film is also quite spiritual in in that sense. Yes, it is. Art is it fully is. Yes.

But you did say that you know she's has a zen-like energy that has been very grounding for you. I was just thinking I'm like do you run your super crazy ideas by her? Like did you tell her that so me and AniRod are going to launch a premium tequila brand and make it good enough to win awards? Like where do these things come from? Well, I think one uh the okay let's forget tequila but anything else as an idea right? Yeah. Like I think where we are in in this world of art and what it has done where commerce and art have met in some ways is we're all creators. we create something. Uh, and when I went into the brand world, I understood they're also creating. They're also telling stories that are shorter, trying to engage not with a story, but through a product in some ways. And we're like, okay, now that's that's pretty interesting. And what I understood was every industry, doesn't matter which one, needs storytelling. Yeah. uh whether you're selling water, whether you're selling a magazine, doesn't matter what you're doing or you're trying to sell an insurance policy in a bank, everybody needs a story. And that's something that I understood. I said, "Okay, this is probably the only way we can an outside world can see structure around us.

The fact that there are larger things to do and and I guess just as a personality, I think I had a colorful life growing up. A lot of tequila happened in my life. So like a partner many people drink a lot of tequila very few say let me just create my own. So this uh these brand friends of mine they say something which is which I think is how I ended up making tequila. He said every extreme consumer becomes a creator at some point. He said and I think it's so true with everything that we do in our life. Like take the movies right? Majority of us didn't go to film school in India itself. We just watch movies like crazy. Yeah. Figured out how to get a job in English and made it. Yeah. And I think that's pretty much the case with everything in my life. You just figured out how to make it yourself. Yeah, that's it.

Yeah. Yeah. You know, I have to tell you though, my favorite part of her interview was she was asked, "What's your favorite possession?" And she said, "It's a Yoda figurine that you've given her." Now, I was like, "This is amazing." I mean, I know what Star Wars has meant to you. It's like the definitive film of of your movie love. Yes. But for Yoda to be a key part of your love story is just so sweet. What is this figurine? Oh, it's it's actually a mold like a handmade mold of a Yoda which we picked up at some point somewhere. And I think when we first met, she said, "Uh, okay, what's something that represents you fully that you can give me and I can keep?" And everything was just pointing to Yoda and nothing else. So I said, "This is all the knowledge. This is where I get everything from. Keep it very carefully. That's so lovely. Yeah. So, yeah, Soda is part of my love story for sure. That's so lovely.

Um, Rana, you started in visual effects, right? And and you've always been very tech forward. So, I assume your anxiety about AI is far less than the rest of us, right? But I found this really amazing. You you were asked that, you know, um is is it obviously the question that everybody's sort of grappling with. Is it going to take over creativity? what happens and you said that the arts are born out of trauma and AI doesn't do trauma. Yes. Ra how trauma shaped you as an artist.

I think all thought in some way say like trauma as a word usually picks a large negative connotation to many things but it's not that it's something that you're deeply affected by and that deep effect could be anything. And sometimes it's conscious, sometimes after you made a certain film or a certain decision, you realize which part of your life it actually played out from. So I think all parts of what you make as a decision, especially in the movies, uh, and sometimes it's eerie when you're developing a story, that type of thing will happen in your real life. So there'll be some strange connect to what you're actually doing. And if you're well rather what I believe is if you're very honest to that filmmaker or that craft or that story you're telling there'll be something which will come out of it which is extremely pure things that you haven't guessed uh that your instincts instinct will lead you there and I think that's what it is right

uh see like it's actually a funny thing I'll tell you I tell you because you know me enough now now like the large part of traumas in my life was say my grandfather's passing was one big part of my life. My health taking a toll was a big part of my life. All of those actually became weapons in some ways of leading a life forward. Like if from the time my granddad had passed, I think the way I have restructured my life into where I know that his void uh is visible. Yeah. and some parts of me have become him and now I do things that he did back in the day. Uh I won't have done that ever say if my health didn't take the turn it did after Bahubali I would have never been part of Amaritra Kata or any of these stories. Uh so I think it's it's what throws you will actually give you a direction which is very different.

uh and I don't think I think only that let me take it back to more simplistic nature right when you use I use a lot of claude and others and I've been testing it out right from the day it's launched and we start testing and we we started checking out trying to create scenes use writers let's see what it is it's always been able to mimic and that's when I came up with the thesis of saying okay listen trauma it's not able to recreate it's able to mimic saying okay this event happened in this person's life. So hence this is how things will be. But what trauma creates is a relationship with a person. How you've reacted to a certain thing that only that's what cinema actually means and that's only created by us. It's where that one beings that are left with super trauma for everything that has and it's also an individual response completely. It can't be a generic team response. Everyone responds differently to a certain thing. Right. So I think that's that's really what uh it can't do. It can help you in plot. It can get your structure together but finally how people react is why we are going to the movies.

Yeah. Yeah. But see you look back now and you can say okay these are the ways in which I was shaped and see the positive sort of turn that life took right but when you were in that moment and you've talked about how post the sort of euphoria of Bahubali you're in America you're eating this saltfree food for months right for and you you give you have to walk away from films because you don't look like that anymore in that moment. And when I see you, I just see positivity. I just see like a can do. Like all the crazy ideas we've discussed, you've never said, yeah, like let's you're like, you know, how did you maintain that despite all of what was happening around you?

I see. Obviously, when you when you break, you break. There's no two ways to that. uh everything that you believed that your life was kind of disappears and it's it's like a strange reset. No, it's like you don't know what's true anymore. You're like, "Oh, this is all not real. It could just go away in seconds, minutes." Then then you start looking inwards and you start realizing how important health is. And also you start realizing how much you've kept yourself in the center of everything. And that's not that's actually not growth. Only if you can remove yourself from the center and people grow around you is actual growth.

And I was like okay now what can I do if I don't like you never uh I've been an actor 10 years by then and you're like okay this is what I thought I'll do all my life and then you'll start uh I had a lot of time your first I think America gives you a lot of time and you're just visiting doctors and hospitals and one awesome thing is it has great bookstores and libraries. Yes. So the only way you spend time is these books or libraries and uh nobody really knows you. So they don't know if you were a thin guy or a big guy. So they don't have a past reference to That's right. Uh so everyone's making comments. Everyone's making comments. And what you start when you have that time but because when you're working you actually don't have that vast of a time to think about life in a long way long and deeper way. you'll start assessing skills of things like okay this is not the only thing I can do you'll start getting to reality of saying uh once this is done you got to go back home you got to figure out life

and I think once you start uh I started I actually did this with a I started writing a list I was like okay what can I do I was like okay I can do voiceovers I said if I can't move that's a start then I kept writing stuff I was like okay I can run these type of business I can come back and do animation I can do then I kept writing writing a list and it was exhaustive. I was like, "Bro, if I can do all this, what am I worried about, right?" And I wrote that I remember for three whole days uh taking time off. Okay, I could do this too. Yeah, it was random stuff. I could run a restaurant like these type of really vague things that kept going on and now sometimes they don't seem so w because I'm doing some of those things. Was it tequila branding? It wasn't in there. But some parts you've done that too.

Yeah. So, so I think once you get a clarity on who you are and saying listen what you are doing isn't the end of your life it's actually what you've defined it as right so then I said okay let's reset that definition and and go forward and again life is back so it's been pretty good and it's this I think it's the same sort of clarity and positivity that also you bring to the table when it's this indie film slate which is of course as we've talked many times before such a labor of love like really pushing a rock uphill of course all we imagine as light ran for seven weeks but then shape of momo it just disappear and such a lovely film yeah it is such a beautiful film it's such a beautiful film right and that has to be heartbreaking how do you sort of then bring this positivity to that and say we'll do it again

see one is it's a new habit like why did we pick parallel cinema. I actually picked it more in the wake of this new technology world kind of taking over, right? And what I really started believing and I started some kind of data where online that we started working with is where people don't engage so much with digital stuff anymore because there's too much of it. Yeah. And what becomes really important is is the need of humans in some ways. Uh what is the difficulty in this? I don't see some some will work, some won't. But what we are actually fighting is a upward wave of exhibition that's not meant for this cinema. It's been built very differently. It's almost like I'm trying to take a a very vintage, beautiful looking car and say, "Listen, let's drive it with this engine with a V2 engine or something. It's just going to blow up." That's not what it's meant to do. Now but what each film is giving us is a is a new uh landscape to enter to understand that oh there's learning from there

and the other thing that is moving which we are actually starting end of the year is newer types of exhibition really yes so we're now building cinemas that are in the 50seater 80seater models where there'll be two or three screens but the idea is it shouldn't feel like a theater it should feel like a coffee shop so you don't have this extreness of going parking downstairs, going up a mall. So, we're trying to create the coffee shop type of uh cinemas which can allow for a cinema which doesn't is not sitting in the mainstream. Where are you building these? We are starting with the first one in UTI. Actually, it's called the assembly rooms in UTI. That's something that we're working on. The the whole project is called the assembly rooms. Second one's in Hyderabad that we're building. Huh. So, Bangalore, we have some one or two facilities. When do you can get to Mumbai? Mumbai real estate is very expensive. Yeah. So I think that will be the last of the cycles but uh but Bangalore Hyderabad should be up soon and the whole in fact September the whole month of September we'll have one small what is it it's like an outdoor cinema that's actually consistently playing the whole month again playing very alternative Telugu films doing some kind of Q&As. I think the standard format for these films also will start changing. It's a slow discovery, but it's a journey that we set ourselves to do. So, and and you're invested enough to now be investing in the actual real estate and creating the platform. The platform for this. Wow. Yes. So, yes, that's the journey we're on now.

Wow. Wow. You know, speaking of Telugu cinema, I was I was talking to Weni Atli last month and I was asking him also. So I was like it just feels like such an exciting time that you you take these sort of big swings. I mean paradise is coming of course the mother of all big swings vanas will come but you also have singam you know you also have raad and and I don't see that in many other places right what is your sense of of what's happening with Telugu cinema right now

see one it's clear there's a variety that's wanted there's a certain past narrative that's kind of done right there there's a small audience for it but it's not really cracking in and the beauty is you always this new set of filmmakers that are there the audience have shifted from hero first to director first really that's been a see I think that's what Raj Modi has done that's what Nagashwin has done Sepa has done pushan has done to some extent so I think all of them have governed their cinema in a certain manner and that's the film that you want to actually go and see uh so I think that that change is a it's an incredible It's a big one. It's a big one. Yeah.

And now if you see languages have kind of disappeared. Subtitles have become a normal thing. Dubbing across languages has become quite comfortable. Even if it's not straight in the theater, there's versions of it sitting in different OTS that everyone is consuming it at in their own form. Right. So I think that's the excitement is always there. See, it's always been the audience that kept supporting new stuff, right? I mean, we watch Telu dubs, Malalam dubs, Tamil dubs. It doesn't matter where it comes from, but there's a tel audience out there that's encouraging you to make cool stuff and I think the filmmakers are just getting braver and braver and somewhere I think next year because of these really big ticket ones coming whether it's uh Vasi Bunny and Atly film spirit all of these are really big films I think the rest of the industry went into saying listen we're going not going to compete big let's just make really unique small films and I think that's what's That's the wake of all of these that you see. So next year, as much as I'm waiting for all the big ones to happen, I know there'll be a series of these really small tiny gems that are actually going to break out.

And somewhere Telugu like Malalam is starting to find its mainstream and alternative edge together sitting in one place. Uh unlike the other industries like I don't know in Bombay how that happens. Yeah. But here Aradu takes up mainstream release. Correct. Mah Babu releases the film. It's not time pass. It's coming at as a big film. Exactly. So I'm saying that's what's uh what's amazing here, right? It is. It gives you a very indie play film of equal chance with a big one. And there's a good chance it can win too. Correct. And you've seen the last bunch of years there've been really small films that have done excessive extremely well. You know, somebody told me next year is like going to be like a 5,000 K year for Telus. It'll be mad. It'll be a mad year for sure. That is insane. We are mad. Of course. Well, if Hollywood Hollywood's done a 10 billion, we should at least get to 5,000 crores. I think that's insane. Okay, tell me this.

You I don't know if you remember this, but you had once told me that the problem with Hindi cinema is there's too much money. Yes. Right. I still think so. There is still too much money. Um, but okay. So, I was at the Voni title reveal and it's the biggest film event I've been to, you know, in recent memory. And of course it's Raja Moly and if it was even a fraction smaller we would be like what the hell you know it it needed to be bigger but is there a is there too much money now in the Telugu film industry and when does money become a problem

you see here that too much money is actually spent on the film right it's spent a lot is spent on the film like if you just go back to budgets of say films like Bahu and I know if you take Vasi also today the cost of talent and all very little That's right. In the scheme of what that film uh there everything is spent on what is on set right so I think that pushing is good and see this is also not these are also not funded films they're also borrowed money films even now so the bigger you push the bigger interest is also being pushed uh unlike there's really very few studios that fund stuff without interest there's no film I can say maybe 10% of films here happen without interest uh whereas There's the other it's the other way around there. Right. So here there's one general fire in you that listen you have to make this money back in the cinemas. Correct. So that heat is correct is that that whole thing of if we sell to OTT we cover the cost profit is made that heated. No it did for a very small time to some people and then OTT was nice enough to just take that cushion away very very fast. So so it's like you're back to the drill. You're back back to just fire in your belly.

Yeah. Yeah, completely. You know, yeah, and but I think that's that's important and and I think the fact that you want the cinema to win in the theater and that if you start making it that way, everything will start changing. Yeah. Because it's not there's no comfort zone in this. It's it's like correct here. What happened is actually to answer your question when OTD started giving that comfort, we started pushing even more. It's like a it gets done here, let's take it to so you're 2x 3x. Yeah. So the risk taking appetite is very high. Number of producers are very high. See you always see a new bunch of 8 10 producers coming in every couple of years in Telugu. And that's not the case in other languages. You don't see an influx of producers. You might see these producers are they are they also willing? They're also risk-taking producers. Full risk takingaking. They're not just sign the biggest star and then do. No. No. They're risk-taking producers. They are liable for the money. They are the guaranters for the money. Correct. That type of producers have entered this place.

Old school Hindi you know right there used to be those stories that if this film flopped Rakkesh Roshan's house would have been sold. You know I mean there are cases like that but also now because of the Telugu community going abroad uh doing so well financially in many other markets some money is inflowing back into cinema in some ways. Correct. Uh I think that gives a huge uh risk-taking capacity when you have these five time producers. See like I meet producers even if it's a first- time producer he might take a first time direct and say listen I want to make this story. So they're not actually working with the star. They didn't come for the star. They came for that story and they thought that story was exciting to produce. Correct. So I think this is what you want to nurture and want to make sure that they're there.

No, because when I saw Raadur, which is the wild swing of wild swings, right? And of course it gets indulgent. I I think it could have done with with, you know, some sort of more more editorial control, but but just for a star as big as Mahesh Babu to back something as unconventional as that is just it's amazing. I I and and that's the thing know when big stars back it there's a notice that things take. they don't disappear away. So they're mount the equal chance that I was talking about. I think that is happening here. Well, and you'll see that even next year. You see next year will have a there'll be a big array of films, but there'll be two or three small films that will come between that and actually make make it out. So that's the exciting part of the movies.

Yeah. Yeah. Tell me as a theater owner, do you feel that the appetite for films in theaters is still as vibrant? It's actually much more vibrant really much more vibrant now than ever. So I think two three things that uh I wouldn't have said this so confidently a year ago but now I will see I think the whole idea of short content all of that came is like like they used to also call it snackable content right there's only so much chips and coke that you'll have in your life after that you will want to watch or eat a proper meal something more nourish yeah so I think the fad of short content is somewhere done you're still cons it's a it's a part of your life, you'll still consume it and consume it always, but that doesn't become the only thing anymore. Yeah. Uh doom scrolling has become a thing. I see a lot of young people turning their phones off. There's a whole generation that is buying flip phones again. So, you know, going back going back to that. So, they know that it's short content is like a drug. It's like you use it too much after that stops working on you and then it doesn't do anything. It's just a routine of things. So I think it's moved away from that and people are starting to watch much more meaningful cinema and somewhere the west was also a clear indicator of that whether it's back rooms obsession Odyssey spider doesn't matter which genre the film is it landed they came they watched so you know that wanting to see big cinema meaningful stuff has happened yeah yeah and what I loved is the the take on films like big films like Odyssey making it so realistic and so approachable. Suddenly AI looks like why do you need this in the movie? Right. So exactly. So that's what he's done which I think is phenomenal.

Like I Okay, speaking of AI, u there was this lovely moment in a Reddit AMA you did where somebody sort of cheekily said to you that um when AI is making the entire film, what job are you going to do? And you said, I'm going to own the AI company. Yeah. I love that. I love that. But as an artist, Ra and as a tech forward artist, do you have rules for yourself about that? Okay, I'll use AI for this, but I won't use it for this.

See, I don't I very little of what we use in AI is going to come on the final screen. I would be very wary of that. Uh because you don't get to test it like how you test actual illusion effects. Uh so one is very little of that part would be used. What would be used is probably many things that are very complex in stunts like digital doubles like you have a body double who's actually risking some parts for you. You might not have him. You might have a digital double altogether. So to me I looking AI at AI completely as an efficiency tool. It's like here you go it takes me x number of hours to do this. This will slash that time by half if not much more. Yeah. So to me it's always that it's not uh is it going to ever replace us? It's pretty impossible. No, of course not. It's it's pretty impossible. And whatever form that you need of it like you will still need the human to be that generator for that uh item.

So there'll be enhanced film making that will happen. You will see diff like how you've se what in our lifetime we've seen different formats from watching a three-hour film we're watching series we're watching short content we like we didn't think of all of this when we were younger like that you'll start seeing formats change we've seen animation we've seen some styles of content coming but now with this tool you'll just start going crazy you can do wild things and I what I'm actually waiting for is that wild stuff to come up it's stuff that you can't innovative stuff yeah it's stuff that you actually can't put the camera and shoot, right? Like here you go. Can you tell me tell me those stories? What's impossible in camera? What's impossible in camera? That's what it's going to do. Like I think it's the edge for here you go. This is all I can shoot. Let me just take tech and push this to the next level.

But but R would you as as a producer, as a filmmaker, as a storyteller, are you okay if a writer will put a story into Claude and it comes out with I mean where where do you stand on those things? So two things like why some part I like it is uh is when many people write in English they don't write very well so Claude kind of cleans up their language it's sometimes easy I make a lot of so she gets better at that so so the it becomes easier to communicate yes okay with plot and stuff like actually this happened a couple of months ago in the office where there were great like log lines and pitches were like super but then minute we met the person then there was nothing correct it get I mean max he'll pass through one filter and get there right it's not going through all filter because finally you have to it's you who are the story that's right and once you meet and then it falls away uh like I said it's a great efficiency tool

what it doesn't do now is uh yet rather it doesn't do vernacular languages very well but I know there are enough of techies around Hyderabad and Chennai who teaching it teaching and making sure that there are products out of AI built for the entertainment ment industry. Uh so like see like you spoke about Claude and the fact that a lot of script writers are writing now I know people who are making some things just for script writers like because they understand the way ideas are generated correct it's more to us it's not generic correct so once things get specialized you will see some products that will change our life like say for example when movie magiculing came out it was such a great tool from bad excels that we were all making suddenly this computer thing just gave stuff and we on floor very quickly or even script writing software right yeah see I'm saying like final draft became such a standard way of working correct so I think it will start setting up these products will start coming out of AI will it entirely replace users no it'll we'll have lesser resistance that's that's what it is correct

but there's there's also a whole school runner of okay I mean Nolan is of course the ultimate purist right but he was he said talked about how he won't even use a thesaurus to look up a word that he's already got in his head because it should be that word in his head. Uh because then don't use a more elevated word. What came out of you is your first instinct. Now, of course, that is a very extreme. We all use thesauruses. It's fine. Uh where do you like where's the line there? See, he is very educated. He knows many words and many things better than all of us. So, I think for little less mortals like us who have not gone to school and studied really well, All of that dictionaries help really quite a bit. It'll up our game 100%. Yes. Yes. I agree. Okay. So, I don't look like a spaz when I'm writing an email anymore. That's right. It's all coherent and good language. Articulated. Yes.

But tell me, what all is spirit doing right now? What are the spirit doing right now? So, there's the theaters. No, assemblies. It's called assembly rooms right now. That's what we decided to call it. Uh so we're building cinema for parl cinema building exhibition for them. This year we're working on a lot of young filmm working with a lot of young filmmakers. So the idea is in the next 18 to 20 months can we bring out five to seven films all made by new filmmakers young first- timers. So that's the in less than two years. Yeah. In less than two years. Yes. And we've been in the process already six months now. Lot lots of film two films are on floor. Uh and that's the idea like we're hoping to just get that new brigade up and I think it's it's time to do that now. Uh so yeah that's happening at spirit at Amaritraata and Tinkle are now uh up now. There's a series being developed in both these companies.

So so yeah so that's been the fun stuff and and uh your Hindi debut as a producer that starts later this year. Yes, we I think in the next week or 10 days we'll know the release date and because there we don't decide release date. The networks do. Correct. So yes, I'm just waiting for the network to give me a release date. I'm done with the film. So is that is that hard to get used to these kind of practices? It's very hard to get used to. See, because you always want the best time for your cinema in the theater and that's always not the best time for the network, right? Because they're doing this monthly thing. they want a film after that. So it is actually a it's it's starting to get a little troublesome. Yeah. Because now we might end up in a place where there are many big films and theatrically we'll have a very small window programming that's going to happen. Correct. Correct. Uh but I don't know how uh Hindi handles this I guess but you know it's very normal in Bombay like yeah they decided okay I'm like really that's how it works

but but yeah and I also think because the north is quite heavily underscreen in comparison I'm starting to notice that more uh as I release films and I mean you yourself own what 300 in these two states only 300 yeah and we're and there are others who own as like that so so these two states are actually comfortable like even like on a sranti when there are three big films we'll release a small indie film within that sector there's enough of an audience there's enough of an audience there screens right so that is starting to get tougher and tougher in the other languages so I realiz okay Telugu we were quite comfortable with heyriv that Friday is free okay let's put it like that's that's a normal way we discuss right right you know it's Hindi gets a little harder yes

did you did you while making the film try and implement any sort of best practices of Telugu cinema in the Hindi film production. See one is see we're working with Manoj uh and Bumman and all of these brilliant amazing actors. Like first day I went to the reading they were by hearted the script so there was nothing for me to say and like shut up just go back and just watch the film and say make it kind of thing that was what it was but again Pratika was there everything was very tight and well done. Yeah. Uh it's just there's no problem that process was not the problem. It was post that what is the theatrical, what is this, who believes in what kind of cinema. Uh so that is a is a harder chariot to pull is in my opinion.

Yeah. So Rana, do you think just the emphasis and the sort of cinema going culture that exists here is is what perhaps is what we haven't nurtured enough in in the north and and and cinema and finally the great sort of cultural influence is when something's in the theaters. Yes, 100%. It's not from streaming. 100% that that is or it's rarely from streaming. It's you have to be in the theater to be mainstream to be part of popular culture. There's no Yeah. Yeah. Definitely.

I think this audience it's a it's a multiplefold. I always keep wondering why this is so awesome and it doesn't emulate in the same way. Yeah. I think one it was the stars and the audiences at that early round that cinema taught them a lot of things like it taught us what gods are. It taught us prayers. taught us how to lead life, how to be with one another. All that came from our cinema to a large part. Like many customs that we have today are customs from film. They're not customs from film was a very big part. They were film based programs. Yeah, they were film based programs. So it's just it's very different. And as time went on that was that continued here.

And another large part is I feel is because the ticket price was controlled. Yes. It was always a low ticket price. So it's affordable. It's affordable. Very few people wanted to actually push things uh like they wanted more people to watch their films. Uh so you cultivated the habit. That habit didn't die. Yeah. Which is why even today if it's a reasonably film that has a decent trailer, it picks up very quickly picks up. Andre this multilanguage thing helped a lot. They get to see variety. They get to see a Tamil film. They know what a Malalam film should look like. Correct. They're literate audience now. Correct. So I think that is something that in that way it's very cosmopolitical. Very. And they take took that same culture and went to the US with them. Yes. Which is when the industry just grew in a beautiful way because of just culture like this. No no it's a very special place and it's a very special industry.

I have one last question. Yes please. I have heard from many people that Rana has one foot in the future. So look into your crystal ball and tell us what is what does it look like for Indian cinema in the next few years. Well, I think the next few years we'll start seeing a lot of what we thought was format is going to change. You will start seeing films without intervals. You will start seeing films of different durations. You will start seeing much longer films in cinemas. Yeah. uh you will have a day pass and go to a cinema theater and spend all day there watching something really very very because habits are changing and that's what people want. They don't want to do the same thing anymore. They want to go to the same place but do something different. Yeah. Uh you will see an extreme surge of live of theater of performers. So I think that's that's actually tremendously changed and that actually give an advent effect to AI. the fact that they're done with it and they want to see real people like just really means a lot. Yeah.

So I think uh we're up to changing like there's a lot that you're going to see and uh I think we have we've we've little bit etched our place and somewhere in the in the global stage but now it's becoming an aspiration for everybody. Exactly. It was never before it was like oh maybe we got there it like something happened but here like we are making this film to get there. Correct. like it didn't happen before. I've never seen parallel film indie filmmakers or mainstream saying listen I want to win the Khan that's why I'm making this film I want to reach the Oscar and I think that's a if one and you see that momentum they'll make it it's not so far since when you start seeing a chunk of entertainment in the globe which we will own. Yeah. So I think that's where the future's lie. So you're all optimistic. I'm very optimistic and I also believe that there'll be a lot of Indian content that will be made globally by global Indians feeding the rest of the world. That's also starting to happen quite fast. So exciting times. Very very exciting times. Excellent. Awesome. I want to come and see a movie in the assembly room. Yes. Yes. Very soon. Love it. Thank you, Rama. Thank you so much. And more power to you for all that you're doing. Continue multitasking. Thank you.`;
