/*
 * Generated by scripts/prefetch-transcript-previews.mjs — do not edit by hand.
 *
 * Preview images for the transcript-import canvases, resolved once and stored
 * under public/. The canvases are rebuilt from code on every mount, so a
 * runtime fetch could never persist; baking them here is what lets a website
 * card render from this app's own origin instead of hotlinking a third party.
 */

export interface TranscriptWebsitePreview {
  path: string;
  mime: string;
  sizeBytes: number;
  width: number;
  height: number;
}

export const TRANSCRIPT_WEBSITE_PREVIEWS: Record<string, TranscriptWebsitePreview> = {
  "https://asana.com": {
    path: "/transcript-import/previews/34dbad98a5d3.png",
    mime: "image/png",
    sizeBytes: 13721,
    width: 1200,
    height: 628,
  },
  "https://bolt.new": {
    path: "/transcript-import/previews/19eb78051cd9.jpg",
    mime: "image/jpeg",
    sizeBytes: 603920,
    width: 2400,
    height: 1200,
  },
  "https://cognition.ai": {
    path: "/transcript-import/previews/8021e6bd6cfb.jpg",
    mime: "image/jpeg",
    sizeBytes: 81335,
    width: 1200,
    height: 630,
  },
  "https://cursor.com": {
    path: "/transcript-import/previews/94e2b6dc31b5.png",
    mime: "image/png",
    sizeBytes: 11076,
    width: 2401,
    height: 1260,
  },
  "https://en.wikipedia.org/wiki/Andrew_Huberman": {
    path: "/transcript-import/previews/c03826499553.jpg",
    mime: "image/jpeg",
    sizeBytes: 359810,
    width: 1280,
    height: 1353,
  },
  "https://en.wikipedia.org/wiki/Baahubali:_The_Beginning": {
    path: "/transcript-import/previews/2a3fb8ac192e.jpg",
    mime: "image/jpeg",
    sizeBytes: 87330,
    width: 263,
    height: 380,
  },
  "https://en.wikipedia.org/wiki/Begusarai": {
    path: "/transcript-import/previews/94b65b166be5.png",
    mime: "image/png",
    sizeBytes: 910081,
    width: 1280,
    height: 637,
  },
  "https://en.wikipedia.org/wiki/D._Ramanaidu": {
    path: "/transcript-import/previews/1477bcde463b.jpg",
    mime: "image/jpeg",
    sizeBytes: 54759,
    width: 300,
    height: 387,
  },
  "https://en.wikipedia.org/wiki/Dylan_Field": {
    path: "/transcript-import/previews/ec37bad965e4.jpg",
    mime: "image/jpeg",
    sizeBytes: 164374,
    width: 594,
    height: 792,
  },
  "https://en.wikipedia.org/wiki/Enter_the_Dragon": {
    path: "/transcript-import/previews/4d108a7870f8.jpg",
    mime: "image/jpeg",
    sizeBytes: 121231,
    width: 263,
    height: 378,
  },
  "https://en.wikipedia.org/wiki/Jan_Suraaj": {
    path: "/transcript-import/previews/afe5b173da31.png",
    mime: "image/png",
    sizeBytes: 154834,
    width: 316,
    height: 316,
  },
  "https://en.wikipedia.org/wiki/Mahatma_Gandhi": {
    path: "/transcript-import/previews/8675f46feded.jpg",
    mime: "image/jpeg",
    sizeBytes: 525574,
    width: 1280,
    height: 1598,
  },
  "https://en.wikipedia.org/wiki/Mahesh_Babu": {
    path: "/transcript-import/previews/35e3afe87ec8.jpg",
    mime: "image/jpeg",
    sizeBytes: 441707,
    width: 675,
    height: 901,
  },
  "https://en.wikipedia.org/wiki/Nitish_Kumar": {
    path: "/transcript-import/previews/c986a297ae10.jpg",
    mime: "image/jpeg",
    sizeBytes: 28148,
    width: 355,
    height: 531,
  },
  "https://en.wikipedia.org/wiki/Prashant_Kishor": {
    path: "/transcript-import/previews/2a8bd322c646.jpg",
    mime: "image/jpeg",
    sizeBytes: 146335,
    width: 1280,
    height: 1363,
  },
  "https://en.wikipedia.org/wiki/Raj_Shamani": {
    path: "/transcript-import/previews/c94a2ad0b762.jpg",
    mime: "image/jpeg",
    sizeBytes: 18983,
    width: 274,
    height: 395,
  },
  "https://en.wikipedia.org/wiki/Rana_Daggubati": {
    path: "/transcript-import/previews/be857365ee46.jpg",
    mime: "image/jpeg",
    sizeBytes: 207606,
    width: 960,
    height: 1273,
  },
  "https://en.wikipedia.org/wiki/Regal_Cinema": {
    path: "/transcript-import/previews/4cddcbe4e76b.jpg",
    mime: "image/jpeg",
    sizeBytes: 328234,
    width: 1280,
    height: 848,
  },
  "https://en.wikipedia.org/wiki/Sensurround": {
    path: "/transcript-import/previews/33a6e3d48b17.png",
    mime: "image/png",
    sizeBytes: 7075,
    width: 1000,
    height: 1000,
  },
  "https://en.wikipedia.org/wiki/Shiva_(1989_Telugu_film)": {
    path: "/transcript-import/previews/085fe7256a7d.jpg",
    mime: "image/jpeg",
    sizeBytes: 77599,
    width: 220,
    height: 300,
  },
  "https://en.wikipedia.org/wiki/Sholay": {
    path: "/transcript-import/previews/dc1728f7ba4a.jpg",
    mime: "image/jpeg",
    sizeBytes: 50632,
    width: 276,
    height: 361,
  },
  "https://en.wikipedia.org/wiki/Where_Eagles_Dare": {
    path: "/transcript-import/previews/80d84bd4c784.jpg",
    mime: "image/jpeg",
    sizeBytes: 41766,
    width: 290,
    height: 217,
  },
  "https://metr.org": {
    path: "/transcript-import/previews/1737da6a38c6.png",
    mime: "image/png",
    sizeBytes: 12335,
    width: 1200,
    height: 628,
  },
  "https://twitter.com/garrytan": {
    path: "/transcript-import/previews/512bd984accb.jpg",
    mime: "image/jpeg",
    sizeBytes: 10235,
    width: 200,
    height: 200,
  },
  "https://vercel.com": {
    path: "/transcript-import/previews/e1b397fc3214.png",
    mime: "image/png",
    sizeBytes: 846782,
    width: 2400,
    height: 1350,
  },
  "https://www.adobe.com/products/aftereffects.html": {
    path: "/transcript-import/previews/dd1d3fe14076.jpg",
    mime: "image/jpeg",
    sizeBytes: 25390,
    width: 1200,
    height: 675,
  },
  "https://www.adobe.com/products/photoshop.html": {
    path: "/transcript-import/previews/7daeb9fd7db7.jpg",
    mime: "image/jpeg",
    sizeBytes: 54729,
    width: 1200,
    height: 630,
  },
  "https://www.adobe.com/products/premiere.html": {
    path: "/transcript-import/previews/d49ec8c39bc2.jpg",
    mime: "image/jpeg",
    sizeBytes: 24039,
    width: 1200,
    height: 630,
  },
  "https://www.figma.com": {
    path: "/transcript-import/previews/8cbd7ec81cf8.webp",
    mime: "image/webp",
    sizeBytes: 1847224,
    width: 1200,
    height: 630,
  },
  "https://www.hubermanlab.com": {
    path: "/transcript-import/previews/7c6e7ef567ee.jpg",
    mime: "image/jpeg",
    sizeBytes: 159979,
    width: 1920,
    height: 1080,
  },
  "https://www.sketch.com": {
    path: "/transcript-import/previews/c4fce4ec3fab.jpg",
    mime: "image/jpeg",
    sizeBytes: 818059,
    width: 2000,
    height: 1000,
  },
  "https://www.warnerbros.com": {
    path: "/transcript-import/previews/b1cdc694572d.png",
    mime: "image/png",
    sizeBytes: 104612,
    width: 1200,
    height: 600,
  },
  "https://www.yovizag.com/50-years-of-jagadamba-theatre-vizag/": {
    path: "/transcript-import/previews/a6041aeb5fbf.jpg",
    mime: "image/jpeg",
    sizeBytes: 53424,
    width: 1200,
    height: 628,
  },
  "https://zeplin.io": {
    path: "/transcript-import/previews/8f57935fc48c.jpg",
    mime: "image/jpeg",
    sizeBytes: 22136,
    width: 1200,
    height: 630,
  },
};

export function transcriptWebsitePreview(
  url: string,
): TranscriptWebsitePreview | undefined {
  return TRANSCRIPT_WEBSITE_PREVIEWS[url];
}
